### ISSUE TITLE
API: Rating service

### ISSUE THREAD

**Issue by bbappserver** [hydrusnetwork/hydrus#379] opened 2020-07-12 20:30 UTC
It would be nice to be able to do get and set the favourite status of items associated to a URL so things like hydrus companion could show favourite status and set favourite status from the browser.

**Comment by thatfuckingbird** [comment] 2020-07-12 20:31
Duplicate of #343

**Closed by thatfuckingbird** 2020-07-12 20:31 UTC
Labels: feature-request

**Comment by bbappserver** [comment] 2020-07-12 20:33
Ah, whoops, I searched for favourites, and didn't see that cause it was under ratings, which is weird given that I subsequently though enough about the issue request to call it the rating service.
