### ISSUE TITLE
Support for other filetypes (xcf in particular)

### ISSUE THREAD

**Issue by puphime** [hydrusnetwork/hydrus#321] opened 2020-06-30 12:01 UTC
As I work in GIMP, I tend to keep my edited files in XCF format to preserve everything i've done (exporting to PSD loses eg. text information). It'd be nice to be able to import them into Hydrus. (without packing them into a zip or 7z first - at the very least i'd like to see support for .gz files)
This also makes me wonder if it wouldn't be useful to be able to import arbitrary file types eg. documents or text files.

**Comment by Zweibach** [comment] 2020-06-30 12:02
Duplicate of #261 
This is even a pinned suggestion, please actually take a look at what already exists.

**Closed by Zweibach** 2020-06-30 12:02 UTC
Labels: feature-request

**Comment by puphime** [comment] 2020-07-02 13:58
Sorry, Totally missed it >_<
