### ISSUE TITLE
A way to apply tag siblings to the stored tag data

### ISSUE THREAD

**Issue by kotauskas** [hydrusnetwork/hydrus#1191] opened 2022-07-08 13:38 UTC
Right now, Hydrus, to the best of its ability, displays sibling tags as the best one of the group, but tags as they are stored are still stored as whatever tag you wrote it as. For example, if you add the tag `funny` to a file and then create a sibling relation `funny` → `song:funny composer - funny song`, the file will still store it as `funny`. If you then delete the sibling relation, the file will revert back to displaying `funny` instead of `song:funny composer - funny song`.

This behavior is a good default for many people because it makes sibling tagging mistakes quickly correctable, but it might create inconsistencies in the long term. Also, it pollutes the sibling relation database quite a bit: if you know that you're never gonna use the old tag name again, you don't exactly want it to be a sibling relation, **you want the worse tag to be destructively converted to the new tag.**

The approach I propose is this: a button called "rewrite" is added to the sibling browser that takes the currently selected sibling relation, goes through all your files and re-tags them according to the sibling relation (remove tag A and add tag B for sibling relation A → B), after which the user can also safely delete the sibling relation if they so desire.

**Comment by Zweibach** [comment] 2022-07-12 18:18
Duplicate of #585
This used to be how siblings worked and there was exactly that function too. It was a catastrophe.

**Closed by Zweibach** 2022-07-12 18:18 UTC
Labels: feature-request
