### ISSUE TITLE
Direct Tag Replacement (Not Siblings)

### ISSUE THREAD

**Issue by BlubParadox** [hydrusnetwork/hydrus#1107] opened 2022-03-27 07:51 UTC
I use some strange software, where Tag Siblings simply don't work in the way that I need them to, while they work well with Hydrus, this program I need to use simply doesn't.

I would like to see the ability to directly mass replace a tag so I can turn Tag A -> Tag B, not make it so Tag A = Tag B.

This might already exist but I don't see it anywhere and I haven't seen anyone talk about it, so I thought i'd do a feature request in case it didn't already exist and others want the same feature, correct me if I'm wrong though, I'll delete this once I have a proper solution.

**Comment by LavyBlack** [comment] 2022-03-27 08:49
Couldn't you just do a search for the tag you want to replace, select all the files that show up, and just replace them by editing their tags?

**Comment by BlubParadox** [comment] 2022-03-27 08:50
You could, but when you're running 2k+ files with 10+ subscriptions, having to constantly do that as new files come in, would be a massive pain. 

I'm looking for a solution which can do it as the files come in.

**Comment by BlubParadox** [comment] 2022-03-31 06:01
It would be extra nice if we could export our sibling links to this new feature if it comes to light.

**Comment by Zweibach** [comment] 2022-04-01 16:02
Duplicate of #585

**Closed by Zweibach** 2022-04-01 16:02 UTC
Labels: feature-request
