### ISSUE TITLE
Gallery 'merge'/'reparse'

### ISSUE THREAD

**Issue by alidan** [hydrusnetwork/hydrus#1111] opened 2022-04-01 10:36 UTC
If you have a gallery downloader open, and you have 2 of the same query in it, or are about to search the same query, would it be possible to have a dialogue that would merge them, or possibly re parse them?

for example, if I searched red_eyes on gelbooru, and a few weeks/months later I forget I searched it, could a dialogue come up to ask me if I want it in a new parse or if I want to re parse from existing?

I can see situations where them being separated is helpful, but I also see removing a 800 image search frees up something along the lines of 20k weight.

Ideally they wouldn't be there for that long for this to happen but I see this as a potentially useful feature. possibly even a reparse button, there are some queries where I want every image and keep researching them over time.

**Comment by CuddleBear92** [comment] 2022-04-01 16:55
duplicate of #498 really

**Closed by CuddleBear92** 2022-04-01 16:55 UTC
Labels: feature-request
