### ISSUE TITLE
Import tags of content that was replaced through duplicate filter

### ISSUE THREAD

**Issue by Fasguy** [hydrusnetwork/hydrus#1087] opened 2022-02-26 18:51 UTC
### The Problem

The duplicate filter doesn't provide the ability to remove known urls from the worse file, when the "this is better" option is selected.

This unfortunately becomes a problem, when trying to gather new tags for a file that was "replaced" through the duplicate filter.
Currently, to get new tags through the url downloader, i need to do this sequence:

- Copy known urls from the superior version of the file
- Paste urls into the url downloader
- Open the file log and hit "try again" on the urls that were part of the inferior file, as these failed with the "Deleted in Duplicate Filter" reason
- Dissolve alternate groups for the inferior file, since they are still marked as related
- Re-queue them into the potential relationships
- Go through the duplicate filter to mark the superior version as "this is better" again

This is a rather lengthy process and makes tag-management quite tedious.

### The Solution

The duplicate filter already provides a way to "move tags from worse to better", but urls can only be copied, not moved.
Adding the option to "move urls from worse to better" would solve this problem, as these urls would then not be attached to a deleted file.

**Comment by Zweibach** [comment] 2022-02-26 18:54
Duplicate of #479

**Closed by Zweibach** 2022-02-26 18:54 UTC
Labels: feature-request
