### ISSUE TITLE
Add option to sort (and collect) by domain_time

### ISSUE THREAD

**Issue by bennyz327** [hydrusnetwork/hydrus#1576] opened 2024-07-27 14:11 UTC
As title

although Hydrus can record domain time very well, it can't be used for searching pages
(especially if I want to look at the timeline on the site, not the timeline I downloaded)

and grouping by domain time is quite useful, because the same post (with multiple file) will have the same domain timestamp, so if Hydrus can group by author-domain_time, I'll get a nice organization without extra work (e.g pixiv post)

I searched for a similar request in the past
#1301

**Comment by Zweibach** [comment] 2024-08-19 18:45
Duplicate of #1301

**Closed by Zweibach** 2024-08-19 18:45 UTC
Labels: feature-request
