### ISSUE TITLE
Gallery Page :: Refresh "Finished" Query

### ISSUE THREAD

**Issue by bbappserver** [hydrusnetwork/hydrus#783] opened 2021-01-13 06:14 UTC
I know we have subscriptions and watchers specifically because some pages update, but it is sometimes the case that I have gotten the gallery of a certain user say off twitter, and I am now impatient and want to get their newer works, and I already have a gallery query for them.  This is especially true for new subscriptions I want to quickly populate or flaky servers I want to manually monitor because I don't trust their error state and I'll forget to retry their errors them if I just dump them immediately into subscriptions.

For this it would be nice to be able to perform a query again, but have it stop as soon as it encounters a post url it has seen before.  Essentially start populating the post list as though the gallery was running for the first time, but stop early once you've gotten to where we were before, there's no need to keep looking at pages we already fetched the urls for.

**Comment by Zweibach** [comment] 2021-01-13 06:17
Duplicate of #545

**Closed by Zweibach** 2021-01-13 06:17 UTC
Labels: feature-request
