### ISSUE TITLE
Crash on Startup in Windows 10 (v500, Qt6)

### ISSUE THREAD

**Issue by nveaa1** [hydrusnetwork/hydrus#1244] opened 2022-09-28 19:13 UTC
### Hydrus version

v500

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Extract

### Install and OS comments

Tested both with an attempted upgrade of v499 as well as a fresh install in a separate directory.

### Bug description and reproduction

Attempting to start Qt6 build on Windows 10 crashes immediately with a log output like the one seen below.

### Log output

```text
v500, 2022/09/28 15:09:40: hydrus client started
v500, 2022/09/28 15:09:40: hydrus client failed
v500, 2022/09/28 15:09:40: Traceback (most recent call last):
  File "hydrus\hydrus_client.py", line 230, in boot
    from hydrus.client import ClientController
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "hydrus\client\ClientController.py", line 38, in <module>
    from hydrus.client.db import ClientDB
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "hydrus\client\db\ClientDB.py", line 16, in <module>
    from hydrus.core import HydrusDB
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "hydrus\core\HydrusDB.py", line 2, in <module>
    import distutils.version
  File "_distutils_hack\__init__.py", line 88, in create_module
  File "importlib\__init__.py", line 127, in import_module
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "setuptools\__init__.py", line 10, in <module>
  File "_distutils_hack\__init__.py", line 88, in create_module
  File "importlib\__init__.py", line 127, in import_module
ModuleNotFoundError: No module named 'setuptools._distutils'

v500, 2022/09/28 15:09:40: hydrus client shut down
```

**Comment by Shangailockdown** [comment] 2022-09-28 19:30
Can confirm the issue is also happening in Windows 11.

>v500, 2022/09/28 21:28:57: hydrus client started
v500, 2022/09/28 21:28:57: hydrus client failed
v500, 2022/09/28 21:28:57: Traceback (most recent call last):
  File "hydrus\hydrus_client.py", line 230, in boot
    from hydrus.client import ClientController
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "hydrus\client\ClientController.py", line 38, in <module>
    from hydrus.client.db import ClientDB
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "hydrus\client\db\ClientDB.py", line 16, in <module>
    from hydrus.core import HydrusDB
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "hydrus\core\HydrusDB.py", line 2, in <module>
    import distutils.version
  File "_distutils_hack\__init__.py", line 88, in create_module
  File "importlib\__init__.py", line 127, in import_module
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "setuptools\__init__.py", line 10, in <module>
  File "_distutils_hack\__init__.py", line 88, in create_module
  File "importlib\__init__.py", line 127, in import_module
ModuleNotFoundError: No module named 'setuptools._distutils'

v500, 2022/09/28 21:28:57: hydrus client shut down

**Comment by lc-guy** [comment] 2022-10-02 14:09
getting this as well on void linux, qt6 ver

**Comment by hydrusnetwork** [comment] 2022-10-12 02:13
Sorry for the trouble here everyone and for responding to this issue late. I rolled out a hotfix for the Windows 500:

https://github.com/hydrusnetwork/hydrus/releases/tag/v500a

And Linux was fixed in 501:

https://github.com/hydrusnetwork/hydrus/releases/tag/v501

**Closed by hydrusnetwork** 2022-10-12 02:13 UTC
Labels: bug
