### ISSUE TITLE
Force Repo Sync/Custom Repo Sync Timing

### ISSUE THREAD

**Issue by Xlaits** [hydrusnetwork/hydrus#823] opened 2021-03-02 14:58 UTC
1d 4h is a long time if you're just hosting a server for yourself. I'd like to have some way of forcing a download of the file/tag repo, or at least some way of setting some form of custom time to check the repo.

I *do* know about the __advanced settings__ option, and while the "download now" and "process now" buttons DO show up, they are greyed out.

![2021-03-02-095748_709x684_scrot](https://user-images.githubusercontent.com/32484365/109667063-c4ce2d80-7b3d-11eb-8ae5-b17d5724de18.png)
 EDIT: Yes, I just realized I screenshot the "tag repos" page. It's the same on the "file repos" tab, too.

**Comment by thatfuckingbird** [comment] 2021-03-02 15:23
Duplicate of #318 ,closing this, upvote that one.

**Closed by thatfuckingbird** 2021-03-02 15:23 UTC
Labels: feature-request

**Comment by Xlaits** [comment] 2021-03-02 16:49
> Duplicate of #318 ,closing this, upvote that one.

Whoops, never showed up on my searches. Sorry!
