### ISSUE TITLE
Exporting file relationships

### ISSUE THREAD

**Issue by DuendeInexistente** [hydrusnetwork/hydrus#1589] opened 2024-09-02 05:36 UTC
Siblings, replacements, the works, is there any way to export all file relationships?

I have a few years old database I fed into by a script that adds tags to the files, and that script's changed a lot, and replaced files don't inherit their tags to the replacements, not to mention file rot leading to files being missing and the like. Is there any way to export the relationships so I can reimport everything without having to redo all the manual work of replacements and siblings?

**Comment by Zweibach** [comment] 2024-09-07 11:19
Duplicate of #423

**Closed by Zweibach** 2024-09-07 11:19 UTC
Labels: feature-request
