### ISSUE TITLE
Namespace substitution tag relationships

### ISSUE THREAD

**Issue by Xeonian** [hydrusnetwork/hydrus#1411] opened 2023-07-23 22:15 UTC
I have a number of files tagged with various values of namespace X that I would like to move or copy into namespace Y. The existing parent/sibling relationships only appear to relate one literal tag to another. It would be convenient to be able to declare a wildcard relationship, and perform substitutions which retain the subtag across namespaces.

As a workaround, I have written a Python script that trawls for tags in namespace X and adds or replaces the corresponding namespace Y tag on corresponding files, but it would be preferable to do this within the relationship system.

**Comment by floogulinc** [comment] 2023-07-23 23:10
Dupe of #589

**Closed by floogulinc** 2023-07-23 23:10 UTC
Labels: feature-request
