### ISSUE TITLE
Detect key conflicts in shortcuts

### ISSUE THREAD

**Issue by novakda** [hydrusnetwork/hydrus#892] opened 2021-05-27 01:52 UTC
(sort of related to #487)

When assigning keys to shortcuts, it's all-to-easy to make one that conflicts with another.

For example, 'Z' by default toggles zoom in the media viewer.     I use letters next to each other as a way to assign similar tags (e.g. q, w, e, r, t, y to assign ratings, or a, s, d, f, g)

The system allows you to create shortcuts that conflict, for example I can assign 'Z' in "media actions, either thumbnails or the viewer" and it may work on thumbnails but in the media viewer it just does the zoom.

It would be nice if the system warned you when trying this, prevent it, or have a way to see all effective key shortcuts in each context (i.e. in the media viewer list all global shortcuts, media viewer shortcuts + any custom user sets being used.

**Comment by Mengmoshu** [comment] 2021-05-27 02:58
Duplicate of #491 .

**Closed by Mengmoshu** 2021-05-27 02:58 UTC
Labels: feature-request
