### ISSUE TITLE
Show if you will add or remove a tag

### ISSUE THREAD

**Issue by dergness** [hydrusnetwork/hydrus#1479] opened 2023-11-09 01:35 UTC
When editing the tags of a single image it's often not evident if you would add or remove a tag from the list.
Yes, you can scroll up to see if it's there, but it would be handy if the list itself would say it.

![image](https://github.com/hydrusnetwork/hydrus/assets/100443007/eddde6f5-02f3-4503-ac80-e441239a6bc8)

I would think adding a character to the front of that list of tag search results could help:
- <kbd>+</kbd> for adding to the current image
- <kbd>-</kbd> for removing the tag
- <kbd>±</kbd> for multiple images where it can either add or remove the tag. It would still open the dialog asking what to do.

So in that case the result box could be
`+ test (5)`
`- testicles (310)`

**Comment by Zweibach** [comment] 2023-11-10 18:59
Duplicate of #610

**Closed by Zweibach** 2023-11-10 18:59 UTC
Labels: feature-request

**Comment by dergness** [comment] 2023-11-11 20:09
Apologies, I move the relevant part there.
