### ISSUE TITLE
Allow modifying files and copy over tags/urls/properties.

### ISSUE THREAD

**Issue by novakda** [hydrusnetwork/hydrus#682] opened 2020-10-11 00:58 UTC
(Tangentially related with #681, #297, and with importing better versions of files and deleting the worse ones)

If you want to edit a file in Hydrus, you have to export, make the edits, import the new file copy over all the properties manually, perhaps using the duplicate files system.

Please provide a way to open a copy of selected files in an external program, then upon returning to hydrus transfer properties to the new edited versions.

e.g. (this assumes #681 or something like it exists):

1. Select file(s) in the thumbnail view or have one open in the media viewer window
1. Right click and select "Edit in Paint.NET" (or Photoshop, or whatever)
1. Hydrus makes a copy of the file in a configured location, and opens that copy in the application.
1. Perform modifications in the program and save.
1. If changes are detected (file no longer binary identical to the original): import the file and transfer URLS, tags, viewing statistics and other properties to the new file.
1. Optionally, delete the orginal file.

The idea is to seamlessly be able to edit files in external applications without worrying about a file's particular hash.  This is particularly useful if you're using Hydrus to manage development/creative files.

**Comment by Zweibach** [comment] 2020-10-11 09:34
Duplicate of #522

**Closed by Zweibach** 2020-10-11 09:34 UTC
Labels: feature-request
