### ISSUE TITLE
Allow copying tags with the keyboard

### ISSUE THREAD

**Issue by thecodewarrior** [hydrusnetwork/hydrus#1205] opened 2022-07-30 22:37 UTC
Currently in order to copy a tag you have to right click the tag, move the cursor over "copy", then move the cursor over to select whether you want to copy with the namespace or not. It would be nice if you could configure which one you prefer and then just use ⌘C to copy it.

**Comment by Zweibach** [comment] 2022-07-30 23:57
Duplicate of #486

**Closed by Zweibach** 2022-07-30 23:57 UTC
Labels: feature-request
