### ISSUE TITLE
File quarantine

### ISSUE THREAD

**Issue by alidan** [hydrusnetwork/hydrus#840] opened 2021-03-25 20:18 UTC
Ok, I won't lie, I download copious threads from the 4 site (not sure what I can say on github, you know the one). one of the threads I enjoy quite a bit is the cyoa's from a and trash, its fun going through those and trying for the best outcome or the most degenerate one depending on the cyoa type, however there is a 72 page unplayable cyoa that gets posted as a troll. 

this is the 15th variation of it I have deleted, its kind of getting annoying. 

so then I had a thought, would it be possible to implement an image quarantine? have the delete records for an exact 'dont re import' but then also have a duplicate search that would quarden off files till you ok them. I want to say everyone on these boards has a troll image or a troll thing that gets posted to pad threads the 'special' individual doesn't like. i'm not even considering implementation as that couldn't be applied program wide due to the stupid amounts of cpu that would take to do and would need to be clamped down on, i'm just wondering if this idea is something that may be worth having? 

generally these images seem to only have a few variants and they end, the one tails comic comes to mind as a 'shock comic' so a few sets of this and its never coming back. but some images someone 'special' just wants to ruin everyone's fun and now that I think 4chan by default has a hash filters, they make new variations often so the hash filter, and by proxy hydruses delete records don't stop anything.

**Comment by Zweibach** [comment] 2021-03-25 20:27
Duplicate of #335
Expand on it if you feel the requested feature wouldn't adequately cover your needs, otherwise it looks like the problem driving the needs are the same.

**Closed by Zweibach** 2021-03-25 20:27 UTC
Labels: feature-request
