### ISSUE TITLE
Persistent popups/notifications that survive program restarts

### ISSUE THREAD

**Issue by roachcord3** [hydrusnetwork/hydrus#1599] opened 2024-09-21 20:09 UTC
I would like for there to be a system for popups to optionally persist after the program restarts, and for this to be exposed via the API. Obviously, the default behavior should be for them not to do that, but I would like to be able to send info via the popup system that requires user acknowledgement, even if their client restarts (due to crash or otherwise.)

My use case is that I want to be able to send a notification to a user when my program is finished doing its work, with a summary of what it did, and I don't want that to disappear if the user restarts the client.

I would be ok if this was implemented more like a typical website's notification system where there is a little bell or whatever that shows how many unacknowledged notifications you have, that acts as a sort of collapsed view for them. I just want the message to persist until the user has acknowledged it, and I want it to be something that Hydrus Web or other similar projects can tap into, rather than just making my program launch a little popup window of its own.

**Comment by floogulinc** [comment] 2024-09-22 02:39
Duplicate of #908

**Closed by floogulinc** 2024-09-22 02:39 UTC
Labels: feature-request
