### ISSUE TITLE
Add URL(s) contained in neighboring txt from manual imports

### ISSUE THREAD

**Issue by Mpegger** [hydrusnetwork/hydrus#1157] opened 2022-06-02 03:37 UTC
When manually importing a file from a local source, tags can be automatically added via a accompanying .txt file. Custom metatags in those accompanying .txt files such as creator: or character: are recognized by Hydrus and added into the local database. However, known source URL(s) for the image being imported cannot be added this way. It would be useful to have a custom metatag that can be used in the .txt so that Hydrus would recognize a URL. For example;

source:http://example.com
url:http://example.com

This way, Hydrus can add the URL and associate the URL as a known URL to the image being manually imported into the users local database, to help keep track of the image.

**Comment by Zweibach** [comment] 2022-06-02 03:41
Duplicate of #377

**Closed by Zweibach** 2022-06-02 03:41 UTC
Labels: feature-request
