### ISSUE TITLE
Cover for unsupported filetypes.

### ISSUE THREAD

**Issue by shin0kaze** [hydrusnetwork/hydrus#1345] opened 2023-03-24 04:42 UTC
This feature is to allow you to store any file in Hydrus.

Cover contains the following fields:
- Image that represents how that file should look;
- Name of that file;
- Extension;
- Notes;
- The file itself.

When Hydrus finds an unsupported file, you can make a cover for it instead. Then, when you search for it you will see the cover of that file.

I know that Hydrus mostly supports images only. But I really like its powerful tag system and speed, so I want to use it for all the collections I have.

**Comment by Zweibach** [comment] 2023-03-31 14:29
Duplicate of #261

**Closed by Zweibach** 2023-03-31 14:29 UTC
Labels: feature-request
