### ISSUE TITLE
Fix truncated tag names when pressing enter too early

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#32] opened 2015-02-28 22:00 UTC
Sometimes when tagging an image or searching for a tag, if you press enter after typing the tag name it will search for or add a truncated version of that tag name. If you wait a second before pressing enter, it's fine.

**Comment by hydrusnetwork** [comment] 2015-11-28 15:44
Thank you for this. Trying to balance fast results with accurate input is a continuing problem. I'm going to improve my new autocomplete less-laggy code this week, and there is a thought of adding an explicit 'search for results now' by hitting tab so users can optionally have better control over how the results load. I also have a long-term plan to partially stream results, as the raw fetching of matching tags only takes about 0.15s--it is the calculation of the tag count that takes all the time.

Perhaps I should ignore key events if they occur while results are loading?

**Comment by ScoreUnder** [comment] 2015-11-30 02:48
Last time I tackled a problem like this, I did it with a daemon thread which could have either 0 or 1 pending tasks. Every time you press a key, it sets the task to update the autocomplete box (overwriting the old task if it's there). Every time the previous task completes, it removes the next task from the pending task area and executes it.

That way if you press 20 keys in less than a second for example, it will do the first search, then only when it completes will it refresh (to do the 20th search, skipping all in between). Then it won't run the search again until you start typing again.

I can't vouch for how optimal this solution is but I can say it "worked for me"!

**Comment by hydrusnetwork** [comment] 2015-12-05 19:13
Thank you, that is useful. I _sort_ of do something like this already, in that I delay the results generation call a few hundred ms after each new key event until a certain number of characters have been entered, where I wait less. That's what you can edit in _file->options->speed and memory_. The results generation call looks at the current value of the textbox, so any intervening key presses won't start separate searches. If the user hits enter before the generation call, it just passes whatever is in the textbox as if it were a choice from the dropdown list. The nice thing is that the results for 'blah' are all contained in the results for 'bl', so I only ever have to query the db once, and then I can filter the cached results after that. The problem is choosing exactly when the user wants results.

Until I can reliably fetch results quickly, I think the current system is an ok balance. I will close this issue for now and maybe we can come back to it once the new system is in place. If I really can get things filtered and appearing in <0.2s, then it might be feasable to kill the delay entirely and fold everything into the gui thread, which might save a lot of this event confusion. The ultimate solution might be in caching the first page of results for every query from 'aaa' to 'zzz' lol.

**Closed by hydrusnetwork** 2015-12-05 19:13 UTC
