### ISSUE TITLE
Favorites/profiles for filename tagging (add before import) dialog

### ISSUE THREAD

**Issue by novakda** [hydrusnetwork/hydrus#678] opened 2020-10-08 00:26 UTC
Using a consistent import tagging scheme can be difficult because you have to recreate all settings in simple/advanced for each import.

Please consider adding something like favorites (like we have for searches) to save/reload these settings. (the dialog that appears when you click add tags before the import).

**Note**  'edit import folder' filename tagging section already does something like this but you have to setup every folder in advance.  What I'm describing is more for importing multiple folders with the same settings on the fly.  To do the same thing with 'import folders' requires:

1. Go to 'manage import folders'
1. Open the desired profile
1. Change the folder path and save
1. Close the settings dialogs
1. Sselect the appropriate option under 'check import folder now'.

**Comment by Zweibach** [comment] 2020-10-08 14:15
Duplicate of #623

**Closed by Zweibach** 2020-10-08 14:15 UTC
Labels: feature-request

**Comment by imtbl** [comment] 2020-10-08 14:28
I think that's not a duplicate.

> Please consider adding something like favorites (like we have for searches) to save/reload these settings.

What does that have to do with

> A setting to add tags from a favourite search to imported files.

?
