### ISSUE TITLE
Allow to automatically tag the search query to the downloaded images

### ISSUE THREAD

**Issue by luckydonald** [hydrusnetwork/hydrus#1405] opened 2023-07-20 10:21 UTC
The option I'm seeking is a simple checkbox which would append tags for the download action.
E.g. 
- `service:derpibooru`,
- `query:cute, pony`

Or
- `service:e621`
- `query:rating:safe`

Some use cases might be:
- if I later realize, the query had many results I don't wanna, it's much easier to get rid of everything and refine the query to start another import.
- I can figure out why a image was downloaded
- Ah, those are my favorites on platform x (because the query is favorite_by:me or similar)
- More ideas others might think of.

**Comment by Zweibach** [comment] 2023-07-22 21:39
Duplicate of #539

**Closed by Zweibach** 2023-07-22 21:39 UTC
Labels: feature-request

**Comment by luckydonald** [comment] 2023-07-28 04:48
@Zweibach Yes, but this one is more specific than the other.
