### ISSUE TITLE
Support for raw pictures

### ISSUE THREAD

**Issue by Kiskadee-dev** [hydrusnetwork/hydrus#1350] opened 2023-03-29 16:21 UTC
Hydrus currently treats .dng raw images as .tiff and works with their very low resolution embedded thumbnails instead of working with the file in its full resolution.

It also exports the images as .tiff

**Comment by Zweibach** [comment] 2023-08-19 22:11
Duplicate of #261

**Closed by Zweibach** 2023-08-19 22:11 UTC
Labels: feature-request
