### ISSUE TITLE
Automatic unarchive

### ISSUE THREAD

**Issue by floogulinc** [hydrusnetwork/hydrus#737] opened 2020-11-21 22:31 UTC
It would be neat if Hydrus could optionally automatically unarchive/unzip downloaded archives, applying the tags from the original archive file and configurable tags based on the file structure within (file and directory names). It could optionally delete the original archive as well. 

An example use case for this is that I subscribe to some artists on Patreon who attach zips or rars of the full res art to the Patreon posts so it would be nice to automatically deal with those. This would also be very nice for importing comics from a watched folder (with filename based page tags).

**Comment by Zweibach** [comment] 2020-11-21 22:35
Duplicate of #524

**Comment by floogulinc** [comment] 2020-11-21 22:36
oh oops I tried to find any existing ones but I guess I didn't search enough.

**Closed by Zweibach** 2020-11-21 22:35 UTC
Labels: feature-request, system:downloading, system:import-export
