### ISSUE TITLE
Copying all tags with counts only copies the tags

### ISSUE THREAD

**Issue by Trizkat** [hydrusnetwork/hydrus#324] opened 2020-07-02 12:40 UTC
## Environment

Hydrus version: 402 - Extract Only
Platform: Windows
OS specifics: Windows 10 Pro 1803

## What happens

When I right click on tags in the selection tags box, go to copy and then use the option all tags with counts. Only the tags show up as copied when I paste then into my text editor.

## Steps to reproduce

1. Right click a tag in the selection tags box.
2. Copy > all tags with counts.
3. Paste into a text editor.

## Desired outcome

I would expect the pasted result to be either in typical CSV format with the desired tags, followed by the mapped count. Or like how they appear inside of hydrus.

**Comment by bbappserver** [comment] 2020-07-03 05:07
This is not a bug it is the intended behaviour, should be tagged as a feature request.
A newlined list of tags is the most useful copy option in the vast majority of cases.

Further there is ambiguity in CSV about column field separators.  There is not typical CSV when any lowercase string without newlines is a legal value in one of the fields, so the format for the new feature should be
```
count tagname
cont2 tagname2
```
Since the integer followed by whitespace and newline are not ambiguous.

**Comment by Mengmoshu** [comment] 2020-07-03 06:21
@bbappserver Did you bother to **think** about the distinction? There's literally no difference between `copy all tags` and `copy all tags with count` right now. **Why else would there be two options?**

This is definitely a bug.

Is there anywhere else in Hydrus that emits CSV? It seems like the logical format for this, but your observations about it don't make it especially clear what your concern is. My understanding of CSV is that either the producer or consumer defines the separator, so the main concern is finding one that isn't allowed in tags.

**Comment by Trizkat** [comment] 2020-07-04 18:46
@bbappserver raises a good point that your typical CSV wouldn't work. Personally I don't mind what format it is in as long as it's reasonably portable

**Comment by hydrusnetwork** [comment] 2020-07-08 01:05
Thank you for this report. I will fix it.

**Comment by hydrusnetwork** [comment] 2020-08-04 18:54
This should have been fixed in v406.

**Closed by hydrusnetwork** 2020-08-04 18:54 UTC
Labels: bug, dev-notified
