### ISSUE TITLE
The concept of collections (sets) for the possibility of organizing related groups of images.

### ISSUE THREAD

**Issue by Shinkir0** [hydrusnetwork/hydrus#1594] opened 2024-09-10 21:54 UTC
Despite the fact that the whole point of hydrus is to get away from the principle of folders, and in the help itself it says that it is not intended for comics and the like, but I just want to voice how I imagine the implementation in terms of the concept of tags.

In general, it would be possible to introduce an additional type of tag that would allow you to group pictures related to the same topic, so that this set would be displayed as something like a folder with a preview of what this set includes.

What I mean is, let's say there is an author of the manga `creator:Yusuke Murata` by making such a request, all the pictures associated with it will be displayed and if we want to group the manga One punch man, for example, then we make a special tag, for example, create a namespace `manga:One punch man` and somewhere in the settings we mark it as a tag set (in general, I think it should be possible to make any tag a collection tag, but I'm not sure about that). And now all files marked with this tag in the general output of images will be displayed as a kind of folder, preferably with a thumbnail showing what lies in this set, for example, by default it shows a random file (or several files) from the set, but with the possibility of manual installation by the user, for example, a comic book cover. When opening such a set, for example, a new tab will open that will display its contents (perhaps when opening the tab, the necessary tags will already be automatically filled in the search field) and if each comic book page has the corresponding tag `page:01`, `page:02`... ...`page:100` then it will be easy to sort them in order.
I also think it would be convenient if the tags of the collection could be nested into each other, perhaps according to the principle of parents and children, `creator:Yusuke Murata` will be the parent for -> `manga:One punch man`, and `manga:One punch man` will be the parent for -> `volume:`, and `volume:` will be the parent for ->`chapter:`

And if it is possible to make any tag a collection tag, then truly limitless possibilities open up :D for example, `creator:Yusuke Murat` and other creators should also be marked as collections and then when requesting creator:* all authors will be displayed as collections and if you click on it, a tab with this author will open where only his pictures and his collections will be, and you can also make it possible to choose whether to open in a new tab or in the current one.

My wild fantasy has played out a lot))).
And you can also add comments to the collection tag, for example, if this is the Author's collection, you can add a brief description of him and links to his Twitter pages patreon and so on.

Although we all came here precisely to get away from the folder system, but we must admit that such a visual grouping was useful, because to be honest, I am not able to remember the names of all the authors, creators and artists who already exist in my collection, especially when the dam of AI generation broke))). And if the query is `ai generated`, `creator:*` 100,000 AI images will be grouped by 1000 authors, life will become a little easier))

P.S. Thank you so much for your efforts, you have done an incredible job!

**Comment by Zweibach** [comment] 2024-09-13 13:24
Duplicate of #310 
Most of this already exists in Hydrus, see: https://hydrusnetwork.github.io/hydrus/getting_started_searching.html#sorting
The little that doesn't exist is already covered by a different feature request.

**Closed by Zweibach** 2024-09-13 13:24 UTC
Labels: feature-request
