### ISSUE TITLE
Text display values for ratings (or something similar to siblings to bind ratings to and from tags)

### ISSUE THREAD

**Issue by novakda** [hydrusnetwork/hydrus#1014] opened 2021-11-24 21:10 UTC
# Feature Description

Something like siblings and parents to generate a "virtual" namespace:tag for each value of a rating service, that can be used just like regular namespace:tags (e.g. grouping, sorting, the top of media viewer and thumbnails, parts of filename for exports, etc.)

Alternatively, a way to specify string values for each rating value in config and add this to displays in the manage tag dialog, etc.

# Background

Ratings can be used to represent things other than degree of quality or how much you like an image.  It can be difficult to recall what each of the rating values means because they don't have text representation (only a star, square, or circle)

For example, you might want to use this to track stages in a media creation workflow. (I use Hydrus as a poor-man's digital asset manager for media production sometimes)

1. Storyboard
2. Draft
3. Ready for QA
4. QA rejected, rework required
5. QA approved
6. Ready for client review

... and so on.

**Comment by Zweibach** [comment] 2021-11-25 21:27
Duplicate of #703

**Closed by Zweibach** 2021-11-25 21:27 UTC
Labels: feature-request
