### ISSUE TITLE
Some tags replaced with [email protected]

### ISSUE THREAD

**Issue by ne80rXHIb8NL** [hydrusnetwork/hydrus#1352] opened 2023-03-30 08:59 UTC
### Hydrus version

v522

### Qt major version

Qt 6

### Operating system

Linux (specify distro and version in comments)

### Install method

Running from source

### Install and OS comments

Pop!_OS 22.04 LTS

### Bug description and reproduction

When downloading from rule34.xxx, certain tags are being replaced, partially or fully, with `[email protected]`.

Examples:
- On images by the creator j@ck, the tag saved is `creator:[email protected]` instead of `creator:j@ck`
- `creator:aruginin@` is saved as `creator:[email protected]`
- `series:the_idolm@ster:_shiny_colors` is saved as `series:the [email protected]: shiny colors`

Not all tags with an `@` are affected. Tags such as `@_@`, `creator:@oz`, `creator:@`, and `creator:tomatto_(@ma!)` are handled as expected.

This may affect other sites, but it did not happen when I tried files with similar tags on Gelbooru.

This issue did not begin in v522; I just noticed these tags on old files and started investigating.

**Comment by Zweibach** [comment] 2023-03-30 21:51
This isn't a Hydrus issue. Rule34 uses a Cloudflare mode that hides what CF thinks is email addresses.

**Comment by Zweibach** [comment] 2023-05-27 19:41
The problem is rare enough and small enough in scope that implementing something to deal with this specifially is not worth it so after talking to dev we've decided to just close it.

**Closed by Zweibach** 2023-05-27 19:41 UTC
Labels: bug
