### ISSUE TITLE
Client API: Get Tag Namespace Colors

### ISSUE THREAD

**Issue by cinnamon-rolls** [hydrusnetwork/hydrus#915] opened 2021-07-02 21:05 UTC
## Context

In `file -> options -> tag presentation`, we have the option to give a color/colour to each namespace. For example, the character namespace is green by default. The creator namespace is red. This Client API addition would allow for a third party application to query the tag colors that the client has set.

## Motivation (Why?)

Querying the tag namespace colors set in the client allows for third party applications using the API to have a more consistent look and feel. If the user recolors the `creator` namespace to hot pink, then 3rd party apps can detect it and adjust themselves accordingly. Similarly, if the user adds some weird personal namespaces, then 3rd party apps can work with them just as seamlessly as Hydrus does.

## What it might look like

In response to a GET request, the client API might return an object. Each key corresponds to a namespace, and each value corresponds to a color. There might also have to be some "magic" for unnamespaced tags.

Hypothetical response:

```json
{
    "none": "#0000FF",
    "character": "#00FF00",
    "creator": "#FF0000",
    "meta": "and so on......"
}
```

**Comment by floogulinc** [comment] 2021-07-02 21:10
Duplicate of #360

**Comment by floogulinc** [comment] 2021-07-02 21:11
I'd suggest copying your post from here to a comment in #360.

**Comment by cinnamon-rolls** [comment] 2021-07-02 21:12
Oops, tried searching for similar keywords to this idea and that one didn't turn up. Sorry for the duplicate.

**Closed by floogulinc** 2021-07-02 21:11 UTC
Labels: feature-request
