### ISSUE TITLE
When I add tags to a file removed by the dupe finder, these tags should go to the better version

### ISSUE THREAD

**Issue by DuendeInexistente** [hydrusnetwork/hydrus#1361] opened 2023-04-27 19:36 UTC
I thought this was how the program worked already tbh. Noticed it isn't by pure chance.

I download and tag my images externally via a script, and so far I had always assumed that, when an image deleted by the dupe finder was added, its tags were redirected to go to the better version. This isn't the case, and it should really be. Ideally it should be done retroactively as well (I must have tens of thousands deleted tagged images because of it) but idk if the needed data is saved. Maybe being able to map it to follow the filename: tag?

**Comment by Zweibach** [comment] 2023-05-03 20:51
Duplicate of #479

**Closed by Zweibach** 2023-05-03 20:51 UTC
Labels: feature-request
