### ISSUE TITLE
Flip on/off a tag and all its siblings

### ISSUE THREAD

**Issue by uwidev** [hydrusnetwork/hydrus#1450] opened 2023-10-01 00:40 UTC
I recently incorporated some spicy images into my Hydrus. PTR on these images are flagged as both `rating:explicit` and `rating:questionable`. When sifting through these images and correcting for inconsistencies, my plan was to use hotkey flip on/off to toggle the tag. However, people have various ways of tagging `explicit` and `questionable` content, such as `e`, `q`, or `nsfw`. When flipping the `rating:questionable`, it only flips that, not the siblings. My proposal is to have a way to flip all related siblings to a particular tag.

Example:
```
rating:q
rating:questionable
rating:explicit

when flipping for rating:questionable...
rating:explicit
```

Of course, we run into the problem of when trying to flip back, we lose some information here. Do we flip back to `rating:q` or `rating:questionable`, and what about all of the other siblings? I think here, we can just flip back to `rating:questionable`, since this is supposed to be the tail of the sibling relationships.

Of course, this feature doesn't just apply to explicit/questionable tags, but to all tags with siblings. I think it would make correcting and standardizing tags for PTR easier. I constantly find myself removing a tag, only to see it not removed because there was another tag that sibling'ed to it.

edit - wording

**Comment by Zweibach** [comment] 2023-10-06 14:44
Duplicate of #327

**Closed by Zweibach** 2023-10-06 14:44 UTC
Labels: feature-request
