### ISSUE TITLE
I'd like a return of the old ratings filter

### ISSUE THREAD

**Issue by Koumeposter** [hydrusnetwork/hydrus#727] opened 2020-11-17 18:32 UTC
Back in version 154, this feature was removed, though I don't know the reasons for it.
Essentially, from memory, you were able to set a range of ratings (for example 1 to 1000), and put your files through a filtering system very similar to the current duplicate filter, where you'd press one button for "Image 1 is better", one for "Image 2 is better", and one for "They're about the same". 
This would keep going until, effectively, all images you'd selected had been through the process, and finalizing would give them all ratings appropriate for how you'd ranked them.

For example, if I put through 5 images, I might get 1 and 4.
I say 4 is better.
It then asks if 4 or 5 is better, and I say 5 is better.
Now, it doesn't need to ask me if 5 is better than 1, since 5>4>1 already.
So next it might ask if 3 or 4 is better. If I now say 3, it might ask if 3 or 5 is better, and if it's still better, it now knows 3>5>4>1
So it will pair up 2 with, say, 4 again, and if it's 4, all it needs to do is ask if 1 or 2 is better. If it's 1, then the ratings should end up like this: 
3 rating:5
5 rating:4
4 rating:3
1 rating:2
2 rating:1

Of course, you could add in many more images, and have some be equal to others, but the process itself remains about the same.

I hope I explained this properly.

**Comment by vickyorlo** [comment] 2020-11-19 09:09
Already mentioned in #154.

**Comment by Zweibach** [comment] 2020-11-19 09:19
Duplicate of #154 
Add onto that one.

**Closed by Zweibach** 2020-11-19 09:19 UTC
Labels: feature-request, system:ratings
