### ISSUE TITLE
Parent & sibling tag view formatting

### ISSUE THREAD

**Issue by shawnshyguy** [hydrusnetwork/hydrus#871] opened 2021-05-06 07:15 UTC
Right now in Hydrus, if you choose to manage tags on a post, you get a very nicely laid out display. Parent tags are indented under the child tag, and sibling tags are shown in parenthesis, like so:
![image](https://user-images.githubusercontent.com/18062048/117255789-0ddd7f00-ae18-11eb-9a05-1c115e0b8cd2.png)
However, this formatting doesn't translate over to other areas, such as "selection tags" on the left-hand side of the files tab:
![image](https://user-images.githubusercontent.com/18062048/117256011-38c7d300-ae18-11eb-987d-91964797dfc5.png)
Although this is most likely intentional, it does make me wish that there were a way to choose which layout to use. I've been using the "selection tags" after searching `system:inbox OR system:archive` to see all my tags, and to see the tag parents indented below the tag here would be rather useful.

**Comment by Zweibach** [comment] 2021-05-07 14:24
Duplicate of #442

**Closed by Zweibach** 2021-05-07 14:24 UTC
Labels: feature-request
