### ISSUE TITLE
Sequentially autotag multiple files via thumbnail selection

### ISSUE THREAD

**Issue by LizardList** [hydrusnetwork/hydrus#1035] opened 2021-12-27 00:12 UTC
Based on this tumblr ask:
https://hydrus.tumblr.com/post/625280834277081088/

If you import multiple images from a comic via URL, you must currently manually tag them all with `page:x`, `chapter:x`, etc. This is a huge pain to do for multiple comic pages.

This requested feature would allow you to do the following:

- Select the thumbnails of imported files, and starting from the first thumbnail selected, add the tag `namespace:1` and increase by 1 every time until all selected thumbnails have been tagged.
- Choose the namespace to be tagged, such as `page:`, `volume:`, `number:`, etc.
- Choose the starting number, so that if you've already added `page:` to the first 3 comic pages, you can autotag the next ones beginning at `page:4`
- Rearrange thumbnails, so that if they're out of order you can put them in order manually before beginning to autotag
- Choose the increase rate. So that instead of tagging `page:1`, `page:2`, `page:3`, etc... you could set the increase rate to +3 and autotag like `page:1`, `page:4`, `page:7`, etc.

**Comment by Zweibach** [comment] 2021-12-27 00:14
Duplicate of #403

**Closed by Zweibach** 2021-12-27 00:14 UTC
Labels: feature-request
