### ISSUE TITLE
System tag/service that keeps track of what files were added via what method

### ISSUE THREAD

**Issue by propeeves** [hydrusnetwork/hydrus#644] opened 2020-09-09 16:47 UTC
I've often found myself wondering which subscription added a certain file, or if it was added via a downloader etc.

While this is possible by adding a tag on each sub, I think it would be easier, visually more appealing, and probably more efficient to do this as a background service or metadata.

**Comment by Zweibach** [comment] 2020-09-09 16:59
Duplicate of #539

**Closed by Zweibach** 2020-09-09 16:59 UTC
Labels: feature-request
