### ISSUE TITLE
Duplicate processing tags: pattern/regex matching

### ISSUE THREAD

**Issue by roachcord3** [hydrusnetwork/hydrus#793] opened 2021-01-26 17:20 UTC
Right now when writing rules for duplicate tag merging, you can either write a tag verbatim or you can write a whole namespace, but as far as I can tell you can't do any pattern matching. I would like to be able to use regexes or at least globs.

Simple use case: I want to merge unnamespaced tags, but not any of the ones from pixiv that are like "series 1000 bookmarks"

Another simple use case: I want to merge namespaced tags, but not any ones that have "tagme" in them (so no "clothing:tagme" or whatever)

**Comment by Zweibach** [comment] 2021-01-26 17:26
Duplicate of #583

**Closed by Zweibach** 2021-01-26 17:26 UTC
Labels: feature-request, system:duplicates
