### ISSUE TITLE
Collections: add "in same duplicate group" and "in same alternate group" or similar

### ISSUE THREAD

**Issue by novakda** [hydrusnetwork/hydrus#1020] opened 2021-12-03 22:46 UTC
(kind of related to #424, at least having similar motivations)

Hydrus stores unique IDs for each alternate/duplicate group internally, but there's no way to group alternates and duplicates together in a search result.

You can get partway there with "view this files relations" and "open > similar looking files" in the context menu, but this only works for one group at a time. "similar looking files" works with multiple files selected, but doesn't distinguish which group they're part of in the results, unless they have other unique tags to go by).

Please add a way to collect results by their duplicates and alternates in the search pages.  Something similar to "open new search pages for each in selection" may also be useful.

**Comment by Zweibach** [comment] 2021-12-04 09:27
Related issue, but for searching instead of collecting #430

**Comment by Zweibach** [comment] 2021-12-04 14:53
...well, I just found out why I thought this issue was familiar.
Duplicate of #431 
Learn to actually check existing issues since this is the third or fourth one in a short time from you specifically I've closed for being a duplicate. And this one is even a dupe of one of your own issues.

**Closed by Zweibach** 2021-12-04 14:53 UTC
Labels: feature-request, system:duplicates, system:searching-sorting
