### ISSUE TITLE
Edit existing tags in-place

### ISSUE THREAD

**Issue by jkendall327** [hydrusnetwork/hydrus#1261] opened 2022-10-30 09:02 UTC
We can edit search predicates in Hydrus, which allows us to alter our queries without typing them out again from scratch.

We should be able to do something similar for existing tags on objects.

For instance, say I have an image where I made a typo in the tag for the artist's name. Currently, I have to copy the existing tag, remove the existing tag, then paste the old tag back in while fixing the typo.

My preferred workflow would be this:
1. Hit F3 to open the tags pane for an object
2. Highlight a tag
3. Hit F2 to open a pane where I can edit the tag in-place, identically to the 'edit predicates' window.

This feature would save me a relatively large amount of time.

I've only considered how this would work in the world of local files and tags, since that's predominantly what I work with. If the design of tag repositories somehow makes this intractable, I'll close the ticket.

**Comment by Mengmoshu** [comment] 2022-10-30 16:59
This isn't an unreasonable feature request, but it's not valuable for the reason of making it take fewer steps. **However** it could be very valuable for producing better petitions on tag repositories. And because of the way tags work in general, it should be more of a `replace this tag with that tag`. For tag repos this could mean that janitors are presented with a petition which clearly indicates that the deletion of a wrong-but-useful tag is accompanied by the addition of the correct version of that tag.

Also, I'm not sure a workflow where you delete the incorrect tag before applying the correct one is wisest. Hydrus doesn't care if you have `creator:tpyo` and `creator:typo` on a file at the same time. The end result is the same, but if for some reason you interrupt your correction process you end up without even a wrong tag to find the file with.

To illustrate what I mean about taking fewer steps:
* If you already have files tagged with the correct spelling of a tag then tag autocompletion should make corrections roughly as easy as your proposed edit in place workflow.

* If you don't have any files with the correct spelling of the tag, but all of the existing misspelled tags are the same, then you only have to do the current procedure once after selecting all of the files with that misspelling.

* If you don't have any files with the correct spelling of the tag, and there are multiple wrong spellings, you can use an OR search or move the results of multiple searches to another page, then use the current procedure in the new page.

**Comment by jkendall327** [comment] 2022-10-30 17:06
Thanks for the comment - I knew when making this PR there would be dimensions I hadn't considered and this illustrated some of them. Your points about it not taking fewer steps mostly makes sense (though I would still like to be able to hit F2 to edit tags, because then it's an identical metaphor to renaming things in every file-browser ever).

I don't know if the specific case I had which prompted me to request this fits with your methods, though. Specifically I want to transform the namespaces of files. When I import things, I give them a default 'filename' namespace to capture whatever info I can, and eventually I go back through, clean them up and replace that with a 'title' namespace (or something equivalent). 

I don't think there's a way to select _n_ files of the same namespace and convert them all to another namespace?

**Comment by Mengmoshu** [comment] 2022-10-30 17:19
I hadn't considered situations where you've got a bunch of unique tags. Smoothing the process would definitely add up there.

**Comment by Mengmoshu** [comment] 2022-10-31 03:08
Turns out this is a duplicate of #585 , although we don't have any mention of adding a keyboard shortcut so you're welcome to head over to that issue and add a comment suggesting we have such a context sensitive shortcut. I'd also suggest it be added to the right click menu for the relevant tag displays.

But since this is a dupe I'm closing the issue.

**Closed by Mengmoshu** 2022-10-31 03:08 UTC
Labels: feature-request
