### ISSUE TITLE
Dual Monitor: Context Menus not shown when hydrus is active on second monitor  

### ISSUE THREAD

**Issue by WorldTeacher** [hydrusnetwork/hydrus#1517] opened 2024-02-06 16:02 UTC
### Hydrus version

460

### Qt major version

Qt 6

### Operating system

Linux (specify distro and version in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

Linux - Garuda Arch
Hydrus: displayed as "installed from source", but I used this package: https://aur.archlinux.org/packages/hydrus

### Bug description and reproduction

I run a dual monitor setup. My main screen is a Samsung Odyssey G9, with a 32" curved monitor above [see here](https://imgur.com/a/da6rCx4)
When hydrus is active on the main screen, the context menu appears at the correct position. If hydrus is dragged to the secondary screen, the context menu (no matter which one) looks like this [broken menu](https://imgur.com/a/5RrmxzU)

**Comment by WorldTeacher** [comment] 2024-02-14 04:26
The about Qt says I'm running 6.6.1

**Comment by hydrusnetwork** [comment] 2024-02-20 22:59
Damn. I have had a couple of reports similar to yours now, too. I didn't realise the AUR ran off your system python and thus libraries update whenever your system does, so the guys who maintain the hydrus AUR package don't have much leeway over which library versions are in use.

I have two monitors, left and right, and going up to 6.6.1 gives my no problems on either screen, so I can't reproduce it. This suggests it is system/Window Manager specific.

So, I am sorry to say that I think this is a bug between Qt and your OS in some complicated coordinate calculation way, and, unless there is an easy 'reset monitor coordinate cache' hack somewhere that fixes it, or I am just being stupid, this is most likely something I cannot fix, and we'd normally have to wait that the next AUR-driven Qt update fixes the regression. If you have used hydrus for a while and this only just appeared recently, when Qt updated, then this is even more likely. The good news is that I think you can get fixed if you move to my 'running from source' method, which allows you to choose which version of Qt you run and will set you back to a more stable version that we know runs well on most systems (and provides multiple alternatives even if not). Please check out the guide here: https://hydrusnetwork.github.io/hydrus/running_from_source.html

Let me know how you get on, and if moving to a different Qt version doesn't fix it, please re-open this!

**Closed by hydrusnetwork** 2024-02-20 22:59 UTC
Labels: bug

**Comment by WorldTeacher** [comment] 2024-02-21 08:23
Hey,

thanks for letting me know. I'll try to set hydrus up from work after work today. It might also be a system related issue, as I've been having some issues tli couldn't pinpoint yet. If running dlfrom source fixes it, I'll post an update here.

**Comment by WorldTeacher** [comment] 2024-02-27 21:49
Hey, sorry for the late response.

So I set up hydrus using source on both my laptop and my pc. My laptop is running Garuda Hyprland, and the pc is running Garuda KDE. I have however noticed one thing:
In KDE (when global menu is enabled) looks like this on the main monitor:
![Screenshot_20240227_223522](https://github.com/hydrusnetwork/hydrus/assets/41587052/737a01f5-1a97-468f-9222-06ede31ecdcd)
In this screenshot, the upper bar is my panel for clock, notifications etc, and the smaller one slightly below is hydrus, where the options are not displayed.

If however, the window is moved to the second screen, which does not have a floating bar, the menu is completely gone. 
This can be mitigated by adding the Application menu to the window decoration, which then looks like this: 
![Screenshot_20240227_223824](https://github.com/hydrusnetwork/hydrus/assets/41587052/533889d2-da77-4a2b-ac20-b4308e798a22)


I'll probably switch to hyprland soon, so this problem will not affect me, but still wanted to let you know that this might be an issue for other users. Idk if it is possible to add the menu bar into the mainwindow, i know it is possible in windows, but i haven't really created a qt gui in Linux yet
