### ISSUE TITLE
Error with urllib3 retry

### ISSUE THREAD

**Issue by rachmadaniHaryono** [hydrusnetwork/hydrus#665] opened 2020-09-26 23:59 UTC
## Environment

Hydrus version: 413, source with pip
Platform: linux
OS specifics: Ubuntu 20.04.1 LTS x86_64

requests: 2.24.0
urllib3: 1.25.10

## What happens

when offline and hydrus send request it may return this error

## Steps to reproduce

1. disconnect from internet
2. add url to download
3. url is not downloaded with  error

## Desired outcome

1. disconnect from internet
2. add url to download
3. url is not downloaded but without error

## Error message / Log file / Screenshots
recent shortened traceback
```python
Traceback (most recent call last):
  File "/home/r3r/git/hydrus/hydrus/client/importing/ClientImportGallerySeeds.py", line 316, in WorkOnURL
    network_job.WaitUntilDone()
  File "/home/r3r/git/hydrus/hydrus/client/networking/ClientNetworkingJobs.py", line 1473, in WaitUntilDone
    raise self._error_exception
  File "/home/r3r/git/hydrus/hydrus/client/networking/ClientNetworkingJobs.py", line 1150, in Start
    response = self._SendRequestAndGetResponse()
  File "/home/r3r/git/hydrus/hydrus/client/networking/ClientNetworkingJobs.py", line 324, in _SendRequestAndGetResponse
    response = session.request( method, url, data = data, files = files, headers = headers, stream = True, timeout = ( connect_timeout, read_timeout ) )
  File "/home/r3r/envs/hydrus/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/r3r/envs/hydrus/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/r3r/envs/hydrus/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/r3r/envs/hydrus/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/r3r/envs/hydrus/lib/python3.8/site-packages/urllib3/util/retry.py", line 429, in increment
    new_retry = self.new(
  File "/home/r3r/envs/hydrus/lib/python3.8/site-packages/urllib3/util/retry.py", line 213, in new
    remove_headers_on_redirect=self.remove_headers_on_redirect,
AttributeError: 'Retry' object has no attribute 'remove_headers_on_redirect'
```
same error from june 2019

<details>
  <summary>retry error</summary>

```python  
AttributeError
'Retry' object has no attribute 'remove_headers_on_redirect'
Traceback (most recent call last):
  File "/home/q/.local/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/q/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/q/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/q/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/home/q/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/home/q/.local/lib/python3.6/site-packages/urllib3/connection.py", line 316, in connect
    conn = self._new_conn()
  File "/home/q/.local/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f3b8ad02748>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/q/git/hydrus/include/ClientServices.py", line 1299, in Sync
    self.SyncDownloadMetadata()
  File "/home/q/git/hydrus/include/ClientServices.py", line 1518, in SyncDownloadMetadata
    response = self.Request( HC.GET, 'metadata', { 'since' : next_update_index } )
  File "/home/q/git/hydrus/include/ClientServices.py", line 957, in Request
    network_job.WaitUntilDone()
  File "/home/q/git/hydrus/include/ClientNetworkingJobs.py", line 1137, in WaitUntilDone
    raise self._error_exception
  File "/home/q/git/hydrus/include/ClientNetworkingJobs.py", line 905, in Start
    response = self._SendRequestAndGetResponse()
  File "/home/q/git/hydrus/include/ClientNetworkingJobs.py", line 1296, in _SendRequestAndGetResponse
    response = NetworkJob._SendRequestAndGetResponse( self )
  File "/home/q/git/hydrus/include/ClientNetworkingJobs.py", line 257, in _SendRequestAndGetResponse
    response = session.request( method, url, data = data, files = files, headers = headers, stream = True, timeout = ( connect_timeout, read_timeout ) )
  File "/home/q/.local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/q/.local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)

  File "/home/q/.local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/q/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/q/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 396, in increment
    history=history)
  File "/home/q/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 195, in new
    remove_headers_on_redirect=self.remove_headers_on_redirect
AttributeError: 'Retry' object has no attribute 'remove_headers_on_redirect'
```
</details>

my attempt to fix this:

- fork urllib3 from 119440a `Add v1.25.10 release to CHANGES on master`
- add following patch

<details>
  <summary>patch</summary>
  
```diff
From bdf3ee48c94322c016dcf34c19d547cb87070365 Mon Sep 17 00:00:00 2001
From: rachmadaniHaryono <foreturiga@gmail.com>
Date: Sun, 27 Sep 2020 06:52:26 +0800
Subject: [PATCH] fix: dev: retry and other

---
 src/urllib3/util/retry.py | 10 +++++++---
 1 file changed, 7 insertions(+), 3 deletions(-)

diff --git a/src/urllib3/util/retry.py b/src/urllib3/util/retry.py
index 3d82832..f0f2591 100644
--- a/src/urllib3/util/retry.py
+++ b/src/urllib3/util/retry.py
@@ -217,14 +217,18 @@ class Retry(object):
             read=self.read,
             redirect=self.redirect,
             status=self.status,
-            other=self.other,
+            other=self.other if hasattr(self, 'other') else None,
             method_whitelist=self.method_whitelist,
             status_forcelist=self.status_forcelist,
             backoff_factor=self.backoff_factor,
             raise_on_redirect=self.raise_on_redirect,
             raise_on_status=self.raise_on_status,
             history=self.history,
-            remove_headers_on_redirect=self.remove_headers_on_redirect,
+            remove_headers_on_redirect=self.remove_headers_on_redirect if hasattr(
+                self, 'remove_headers_on_redirect'
+            ) else frozenset(
+                [h.lower() for h in self.DEFAULT_REDIRECT_HEADERS_BLACKLIST]
+            ),
             respect_retry_after_header=self.respect_retry_after_header,
         )
         params.update(kw)
@@ -407,7 +411,7 @@ class Retry(object):
         read = self.read
         redirect = self.redirect
         status_count = self.status
-        other = self.other
+        other = self.other if hasattr(self, 'other') else None
         cause = "unknown"
         status = None
         redirect_location = None
-- 
2.25.1

```
</details>

**Comment by imtbl** [comment] 2020-09-28 18:30
The diff you posted is a urllib3 patch. So is this an urllib3 bug or an issue of Hydrus not handling the error correctly?

Please add more details about the actual error (ideally, the error log message) occuring in Hydrus.

**Comment by rachmadaniHaryono** [comment] 2021-05-01 16:26
## Environment

Hydrus version:437, with pip and pyenv
Platform:LInux
OS specifics:Ubuntu 21.04 x86_64 

## What happens

download failed when internet disconnected

## Steps to reproduce

1. download image
2. disconnect internet while downloading image


## Desired outcome

no error

## Error message / Log file / Screenshots

```python

type object 'Retry' has no attribute 'other'… (Copy note to see full error)
Traceback (most recent call last):
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/home/r3r/.pyenv/versions/3.8.7/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/home/r3r/.pyenv/versions/3.8.7/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/home/r3r/.pyenv/versions/3.8.7/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/r3r/.pyenv/versions/3.8.7/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/r3r/.pyenv/versions/3.8.7/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/r3r/.pyenv/versions/3.8.7/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='i.4cdn.org', port=443): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/urllib3/util/retry.py", line 596, in __getattr__
    return getattr(super(Retry, self), item)
AttributeError: 'super' object has no attribute 'other'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/r3r/git/hydrus/hydrus/client/importing/ClientImportFileSeeds.py", line 1379, in WorkOnURL
    self.DownloadAndImportRawFile( file_url, file_import_options, network_job_factory, network_job_presentation_context_factory, status_hook )
  File "/home/r3r/git/hydrus/hydrus/client/importing/ClientImportFileSeeds.py", line 601, in DownloadAndImportRawFile
    network_job.WaitUntilDone()
  File "/home/r3r/git/hydrus/hydrus/client/networking/ClientNetworkingJobs.py", line 1516, in WaitUntilDone
    raise self._error_exception
  File "/home/r3r/git/hydrus/hydrus/client/networking/ClientNetworkingJobs.py", line 1174, in Start
    response = self._SendRequestAndGetResponse()
  File "/home/r3r/git/hydrus/hydrus/client/networking/ClientNetworkingJobs.py", line 340, in _SendRequestAndGetResponse
    response = session.request( method, url, data = data, files = files, headers = headers, stream = True, timeout = ( connect_timeout, read_timeout ) )
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/urllib3/util/retry.py", line 517, in increment
    other = self.other
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/urllib3/util/retry.py", line 598, in __getattr__
    return getattr(Retry, item)
AttributeError: type object 'Retry' has no attribute 'other'
```

<details>
  <summary>pip freeze</summary>
  
  ```
attrs==20.3.0
Automat==20.2.0
beautifulsoup4==4.9.3
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
cloudscraper==1.2.58
constantly==15.1.0
cryptography==3.4.7
html5lib==1.1
hyperlink==21.0.0
idna==2.10
incremental==21.3.0
lxml==4.6.3
lz4==3.1.3
nose==1.3.7
numpy==1.20.2
opencv-python-headless==4.5.1.48
Pillow==8.2.0
psutil==5.8.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pylzma==0.5.0
pyOpenSSL==20.0.1
pyparsing==2.4.7
PySide2==5.15.2
PySocks==1.7.1
python-mpv==0.5.2
PyYAML==5.4.1
QtPy==1.9.0
requests==2.25.1
requests-toolbelt==0.9.1
Send2Trash==1.5.0
service-identity==18.1.0
shiboken2==5.15.2
six==1.15.0
soupsieve==2.2.1
Twisted==21.2.0
urllib3==1.26.4
webencodings==0.5.1
zope.interface==5.4.0
  ```
</details>

**Comment by rachmadaniHaryono** [comment] 2021-05-01 16:27
similar issue from quick google search

https://github.com/psf/requests/issues/5782

**Comment by hydrusnetwork** [comment] 2021-05-05 16:02
After some discussion and searching, I think this may be a thread safety issue in urllib3--or requests' handling of urllib3's connection pool--when dealing with connection failures for the same requests Session across multiple threads. It does occur in requests 2.25.1 and does not seem to occur with 2.23.0, so I have updated hydrus's requirements.txt to just go with 2.23.0, and I have hacked in an error catch for the specific error text here to try to just treat it like a regular connection failure, and retry again a bit later. We'll see how that works out.

We'll also see if the problem is fixed in a future requests/urllib3 version, or if there is better guidance for multi-threaded Session use.

**Closed** 2021-05-05 20:13 UTC
Labels: bug

**Comment by rachmadaniHaryono** [comment] 2021-05-06 02:26
error still exist on v438

```python
'Retry' object has no attribute 'remove_headers_on_redirect'… (Copy note to see full error)
Traceback (most recent call last):
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fbe57fd1eb0>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/r3r/git/hydrus/hydrus/client/importing/ClientImportFileSeeds.py", line 1379, in WorkOnURL
    self.DownloadAndImportRawFile( file_url, file_import_options, network_job_factory, network_job_presentation_context_factory, status_hook )
  File "/home/r3r/git/hydrus/hydrus/client/importing/ClientImportFileSeeds.py", line 601, in DownloadAndImportRawFile
    network_job.WaitUntilDone()
  File "/home/r3r/git/hydrus/hydrus/client/networking/ClientNetworkingJobs.py", line 1516, in WaitUntilDone
    raise self._error_exception
  File "/home/r3r/git/hydrus/hydrus/client/networking/ClientNetworkingJobs.py", line 1174, in Start
    response = self._SendRequestAndGetResponse()
  File "/home/r3r/git/hydrus/hydrus/client/networking/ClientNetworkingJobs.py", line 340, in _SendRequestAndGetResponse
    response = session.request( method, url, data = data, files = files, headers = headers, stream = True, timeout = ( connect_timeout, read_timeout ) )
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
    new_retry = self.new(
  File "/home/r3r/.pyenv/versions/hydrus/lib/python3.8/site-packages/urllib3/util/retry.py", line 213, in new
    remove_headers_on_redirect=self.remove_headers_on_redirect,
AttributeError: 'Retry' object has no attribute 'remove_headers_on_redirect'
```
<details>
  <summary>pip freeze</summary>
  
  ```
  attrs==20.3.0
Automat==20.2.0
beautifulsoup4==4.9.3
certifi==2020.12.5
cffi==1.14.5
chardet==3.0.4
cloudscraper==1.2.58
constantly==15.1.0
cryptography==3.4.7
html5lib==1.1
hyperlink==21.0.0
idna==2.10
incremental==21.3.0
lxml==4.6.3
lz4==3.1.3
nose==1.3.7
numpy==1.20.2
opencv-python-headless==4.5.1.48
Pillow==8.2.0
psutil==5.8.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pylzma==0.5.0
pyOpenSSL==20.0.1
pyparsing==2.4.7
PySide2==5.15.2
PySocks==1.7.1
python-mpv==0.5.2
PyYAML==5.4.1
QtPy==1.9.0
requests==2.23.0
requests-toolbelt==0.9.1
Send2Trash==1.5.0
service-identity==18.1.0
shiboken2==5.15.2
six==1.15.0
soupsieve==2.2.1
Twisted==21.2.0
urllib3==1.25.11
webencodings==0.5.1
zope.interface==5.4.0
```
</details>

**Comment by hydrusnetwork** [comment] 2021-05-12 02:01
@rachmadaniHaryono Thank you, I am sorry for the trouble. I had another look into the core cause for this problem, which I have had trouble really explaining, and now I believe it could be due to the way I have been serialising and restoring sessions. I have improved the way I do this for tomorrow's release. All fixes will apply for you automatically on update. Please let me know if you still have this in 439!
