### ISSUE TITLE
Non-destructive filter for pages

### ISSUE THREAD

**Issue by CatPlanet** [hydrusnetwork/hydrus#1016] opened 2021-11-25 19:36 UTC
So basically, as for now, we have option to "open files->my files" and do our search there, which is backbone of Hydrus:
![](https://i.imgur.com/88V16zp.png)

But there are other ways to get our files. For example: when we click new imports. Or galleries page. Or send selected items to new page. Probably more but those are I use quite often. This bare minimum what we see:
![](https://i.imgur.com/UJqByFD.png)

There is something missing, and that we can't do any real search with it.
Of course, we can click on tags and "select" appropriate files, same with inbox/archive items. Another "hack" is sorting files by, for example, duration and select files with duration.

But if one is in need of doing a "little less basic" tag logic search, anything with willcards or namespaces, having in-between duration/date modified/dimension searches etc, or plainly not wanting to clicking through "select + send to new page" ten times and then closing all windows created this way - then I'd love to propose toggeable filtering search thingy.

![](https://i.imgur.com/MBW6xpj.png)

Click filter icon
Filter search menu expands
All searches are non-destructive (filtered elements are only hidden from view).
Simple as.

**Comment by Zweibach** [comment] 2021-11-25 21:23
Duplicate of #467

**Closed by Zweibach** 2021-11-25 21:23 UTC
Labels: feature-request
