### ISSUE TITLE
Parent Tag can't be removed because it is not showing in the Parent Tag Manager

### ISSUE THREAD

**Issue by HASJ** [hydrusnetwork/hydrus#128] opened 2015-12-20 02:44 UTC
![tag parents existant but missing](https://cloud.githubusercontent.com/assets/9345660/11916128/5e1dfb90-a6b0-11e5-9f9f-9f07a08f9f72.png)

At first I thought it was because the parent tags were made into siblings for others (semen on face < cum on face, etc.) but I haven't changed the face tag.
![tag child there but not all tags](https://cloud.githubusercontent.com/assets/9345660/11916173/90a84398-a6b2-11e5-8e04-049583bab3b8.png)

The other tags do not show as either child nor parent to any other tag.
I **do** remember adding these parent tags, so what is happening?

**Comment by hydrusnetwork** [comment] 2015-12-22 20:17
I can't quickly reproduce this, but the inner workings of these dialogs is pretty arcane, and I would not be surprised is some things will not show for a peculiar reason. I need to put some time into making them better. Some thoughts:

I notice you have swallowing->gokkun sibling. Do you have any pairs for 'swallowing->something'?

If you open the manage tags dialog on a file and jump to 'local tags' and put in 'gokkun', do you still get 'face' as a parent there?

If you reboot the client, is it fixed?

Do you have 'apply all parents to all services' checked in _file->options->tags_?

Can you remember ever adding 'face->something', either as sibling or parent? It might be that an invalid loop has been created, so the dialog is hiding part of the circular chain.

If you scroll to the very top and bottom of the list, are there any pairs with a (-) or (+) in the first column? Something might have got the wrong status and not being sorted correctly.

I have a job to convert the tag autocomplete dropdowns in the siblings and parents dialogs to something that won't convert sibling and parent relationships, since you are viewing and editing those pairs in a 'raw' manner, and so you should see them in the same way. I was expecting to do it as part of the planned future work on these dialogs, but perhaps I should bump it up. It might not fix this problem, but it would make these sorts of things easier to navigate and diagnose.

**Comment by HASJ** [comment] 2015-12-22 23:33
>I notice you have swallowing->gokkun sibling. Do you have any pairs for 'swallowing->something'?

Nope. No parent tag, only swallowing > gokkun.

>If you open the manage tags dialog on a file and jump to 'local tags' and put in 'gokkun', do you still get 'face' as a parent there?

![clipboard01](https://cloud.githubusercontent.com/assets/9345660/11968266/aa9cf762-a8f1-11e5-91d3-2bf621c27e9a.jpg)

>If you reboot the client, is it fixed?

Nope.

>Do you have 'apply all parents to all services' checked in file->options->tags?

Yes.

>Can you remember ever adding 'face->something', either as sibling or parent?

Nope but I think I found out what is happening. Holy shit what a mess.

I have cum on face > semen on face then sex as parent for that.
The public tag repo has cum on face / cum on head (which becomes semen on head in my db) / face

![clipboard01](https://cloud.githubusercontent.com/assets/9345660/11968438/6a1cf988-a8f3-11e5-9fcf-269994d55945.jpg)

**Comment by CuddleBear92** [comment] 2020-06-13 19:19
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).

**Closed by CuddleBear92** 2020-06-13 19:19 UTC
Labels: old-issue
