### ISSUE TITLE
Client API: searching and sorting via system predicates

### ISSUE THREAD

**Issue by thatfuckingbird** [hydrusnetwork/hydrus#351] opened 2020-07-07 19:41 UTC
Support system predicates and sorting in the API just like in the main UI.

**Comment by floogulinc** [comment] 2020-07-09 06:50
The sorting portion of this is a duplicate of #236.

**Comment by hydrusnetwork** [comment] 2021-07-27 01:45
Searching for most system predicates is done for this week's release! It uses your system predicate parser, so it supports those to start with. I will have some proper documentation for all supported types.

I will not close as I don't have sort yet--that's still stuck on newest import time first.

**Comment by hydrusnetwork** [comment] 2021-08-11 21:20
Ok, this should be done now!

https://hydrusnetwork.github.io/hydrus/help/client_api.html#get_files_search_files

I will give this another pass to improve the help, specifying exactly what asc/desc is for each type!

**Closed by hydrusnetwork** 2021-08-11 21:20 UTC
Labels: feature-request, system:api
