### ISSUE TITLE
Split database file storage locations by file domain

### ISSUE THREAD

**Issue by klasmodd** [hydrusnetwork/hydrus#1146] opened 2022-05-19 20:06 UTC
It may be useful to store files of different domains in different folders.

Say, I have a giant **booru** domain which I don't want to backup since files can be redownloaded, and also have a small **IRL** file domain which I want to backup regularly.

Right now all these files are stored in a single location, **client_files**. So, I either have to regularly backup my entire storage to save my `IRL` files, or have to devise some batch processing (like creating a list of all **IRL** files to copy), or have to abandon making backups.

I propose an option for **migrate database** dialog, allowing to choose files of what domain are to be saved at what location.
**Thumbnails** may still all sit in a single folder.

Such an option would help at making backups or moving files of a single domain, without changing other domains' files. It may also help people who have different external routines for different file domains. For example, I resize **booru** images, but I do not do so with **IRL** ones.

**Comment by Zweibach** [comment] 2022-05-19 20:08
Duplicate of #338

**Closed by Zweibach** 2022-05-19 20:08 UTC
Labels: feature-request
