### ISSUE TITLE
merge selected gallery queries to one.

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#639] opened 2020-09-02 04:27 UTC
Want to be able to merge selected gallery queries to one.
If there is a limit that it needs to match gug then thats fine.
This could enable easier load reducal quickly as merging two or more queries on the game site should also not add any duplicated post urls, cuttign the load on those aswell as general UI. 

An option to requery the queries might be a good idea along with other issues that might work with it. #633

**Comment by Zweibach** [comment] 2020-09-02 05:18
Duplicate of #498

**Closed by Zweibach** 2020-09-02 05:18 UTC
Labels: feature-request, system:downloading, system:user-interface
