### ISSUE TITLE
Group files with their alternates

### ISSUE THREAD

**Issue by AkiBismarck** [hydrusnetwork/hydrus#1365] opened 2023-05-07 08:36 UTC
A collect function to group/collect files with their alternates.
Maybe also duplicates, but my personal concern in the moment would be mainly alternate files.
This would simplify tagging variants of files which are badly tagged and could enable to uniquely identify file groups based on "similarity". 

My current workaround to archive something like this is to tag all files that belong together with the same ID(Random Hash) tag, which is tedious when you have a lot of file alternates which sometimes are just 2 files.

**Comment by Zweibach** [comment] 2023-05-07 09:26
Duplicate of #431

**Closed by Zweibach** 2023-05-07 09:26 UTC
Labels: feature-request
