### ISSUE TITLE
More shape options for rating display

### ISSUE THREAD

**Issue by novakda** [hydrusnetwork/hydrus#1015] opened 2021-11-24 21:16 UTC
Please consider adding more shape options for the rating display.   With more than three rating services, and if you have a mix of like/dislike and numerical rating ones, it can be difficult to distinguish them.

Using Unicode characters instead of shapes would let you use interesting ones like Ⓛ, ❶, or emoji .

(similar motivations to #1014)

**Comment by Zweibach** [comment] 2021-11-25 17:46
Duplicate of #320

**Closed by Zweibach** 2021-11-25 17:46 UTC
Labels: feature-request
