### ISSUE TITLE
Add HEIC/HEIF image support

### ISSUE THREAD

**Issue by ruixingchen** [hydrusnetwork/hydrus#1152] opened 2022-05-28 03:28 UTC
HEIF will cut 50%  disk usage down, that should be nice

**Comment by Mengmoshu** [comment] 2022-05-28 04:39
I didn't like how rude the title was so I fixed it. Talking about the timing of a feature request as part of the title is kinda gauche. Then you fail to even talk about what circumstances support that claim.

Is HEIC/HEIF a widely used distribution format yet? Are standards and libraries consistent and at least a little stable? Are you assuming that for this feature people (or worse the client) will be reencoding images to the new format?

To most of us, disk is cheap, changing file hashes is expensive.

**Comment by Zweibach** [comment] 2022-05-28 11:23
Duplicate of #261

**Closed by Zweibach** 2022-05-28 11:23 UTC
Labels: feature-request
