### ISSUE TITLE
system:limit doesn't work as intended with OR grouping

### ISSUE THREAD

**Issue by propeeves** [hydrusnetwork/hydrus#917] opened 2021-07-04 22:56 UTC
## Environment

Hydrus version: 445
Platform: Linux
OS specifics: Artix

## What happens

When using OR searches with system:limit, the number of items returned is randomly chosen and is both below the set limit and below the amount of items remaining in the database. 

## Steps to reproduce

1. Set a global system:limit
2. Search using OR
3. Turn off system:limit and compare amount of results returned

## Desired outcome

A number of items equal to either the system:limit or the number of matching items in the database is returned, whichever is lower.

**Comment by hydrusnetwork** [comment] 2021-07-12 02:28
Thank you, I will check this out! I have had similar from another user this week as well.

**Comment by hydrusnetwork** [comment] 2021-07-13 23:27
Thanks again. I had a good look at this, but unfortunately I was unable to reproduce the problem. I played with high and low explicit system:limit and implicit global system:limit, and OR with system preds or tags, but I always got the limit number (or accurately fewer) files back, and always the same on refresh. I did find some bad OR/limit logic, though (limits and file sorts applying to the sub-searches in an OR), so I have tightened that up, and I think I fixed one search type where the OR predicates could be run twice, but I am not sure if the things I fixed could have caused your issue unless the top level search had an explicit system limit and the global system limit under _options->speed and memory_ were very small.

So, please give tomorrow's release a try when convenient and let me know if things are better. If not, can you give some more specific examples on the queries giving you trouble? I don't need to know the exact tags, but the overall types and rough counts, and the file sort e.g.:

> (file sort: random)
> series:AAA (~3,000) OR series:BBB (~15,000)
> global system:limit=5000
> on 'my files/'all known tags'
> 
> Gives results in range 2,800-3,000.

The other report I have very similar to this issue has far smaller numbers, and also has system:inbox and a -namespace:anything in there, but I could not reproduce that either. Do you experience the problem just with a bare OR as in that example, or do you have some more search predicates in there? How many items are in the OR, and how big are they approx?

Anyway, let me know how you get on with 447!

**Comment by hydrusnetwork** [comment] 2021-07-20 20:57
I have had a report this is fixed now, so I am closing this. Let me know if you still have it!

**Closed by hydrusnetwork** 2021-07-20 20:57 UTC
Labels: bug, dev-notified
