### ISSUE TITLE
Ability to paste tags without opening manage tags dialog

### ISSUE THREAD

**Issue by novakda** [hydrusnetwork/hydrus#407] opened 2020-07-24 03:36 UTC
To copy one or more tags between files currently, you have to

1.  Copy the selected tags from the manage tag dialog.
2.  Select the target file(s).
3.  Open the manage tag dialog for the target file(s)
4.  Select the "Paste newline-separated tags from the clipboard into here" icon.
5.  Close or apply changes.

It would be nice to be able to apply tags in the clipboard to a selection without having to open the manage tag dialog.

This is especially useful if you're copying and pasting tags with multiple files in the media viewer.

**Comment by bbappserver** [comment] 2020-07-25 08:48
Overlaps with #250

**Comment by Zweibach** [comment] 2020-07-25 21:39
Duplicate of #250 

Since you can already copy tags with right-clicking them in the side-bar, 250 would do the rest of the functionality requested here and would require the same base functionality to be possible far as I know.

**Closed by Zweibach** 2020-07-25 21:39 UTC
Labels: feature-request, system:tag-management
