### ISSUE TITLE
error "Could not find a file or post URL to download!" on various boorus

### ISSUE THREAD

**Issue by PixivAddict** [hydrusnetwork/hydrus#852] opened 2021-04-16 18:22 UTC
## Environment

Hydrus version: 435 exec
Platform: Win7

## What happens

Fails to download image from "url import" and/or using the gallery downloader
(please replace xx with tt:)
hxxps://danbooru.donmai.us/posts/2754672
hxxps://danbooru.donmai.us/posts/3259867
hxxps://e621.net/posts/2662369
hxxps://e621.net/posts/2659888
with a message Could not find a file or post URL to download!

**Comment by Aegis43615** [comment] 2021-04-16 18:37
First one is paywalled due to explicit content, I assume you could download if you have an account and send the cookies. Or just use gelbooru with a fringebenefits cookie if it's there.
Second one was removed for being a banned artist
Third and Fourth are on e621's global blacklist so you would need to login then send the cookies to hydrus to be able to download. This can be done through hydrus companion or other ways.

Not a bug though.

**Comment by PixivAddict** [comment] 2021-04-16 18:43
I have a login for danbooru im using, but it didnt help here?  I'll look at hydrus companion thanks

**Comment by PixivAddict** [comment] 2021-04-16 19:06
Oh, using hydrus commpanion and sending cookies from e621 (i had an account) and it worked.
About danbooru, sending cookies here works too. 

I entered the logins correctly onto hydrus, is that no longer enough?  Hydrus companion is now a must have?

**Comment by Zweibach** [comment] 2021-04-16 21:14
Closing since this is a user error, not a bug.

**Closed by Zweibach** 2021-04-16 21:14 UTC
Labels: bug
