### ISSUE TITLE
DisplayVersion value isn't being added to registry

### ISSUE THREAD

**Issue by ehawman** [hydrusnetwork/hydrus#1071] opened 2022-02-17 04:16 UTC
### Hydrus version

473

### Operating system

Windows 10

### Install method

Installer

### Bug description and reproduction

No version info in Programs & Features or seen by winget.

winget says the version is "Unknown", and the Programs & Features window has no Version number. (Unfortunately this causes winget to reinstall Hydrus *every. single. time.* you run `winget upgrade --all`. Mucho bad. I bet your repeated DL numbers to the same IPs went up when the manifest was added to winget.

So right now I have two theories:

1.  Because of the `#ifndef Version` check at the top, we aren't throwing errors if a version number hasn't been defined. No version number means Version=Null means Inno doesn't even put a version entry in the registry. If this is the case, I think you should remove that check and instead do a try/catch block somewhere to ensure that a version number is included.

2. We're missing a [Registry] section. I went through the Inno Setup Compiler's wizard, accepting all default values, and I found that you can manually set registry entries. The following block *might* do it. I am strongly leaning towards #1 as the culprit, though.

``` iss
[Registry]
Root: HKLM; Subkey: "SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Hydrus Network_is1"; ValueType: string; ValueName: "DisplayVersion"; ValueData: {#Version}
```

For reference, this is my registry entry at `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Hydrus Network_is1`

![Untitled](https://user-images.githubusercontent.com/52979227/154402655-6036893a-9454-4b47-a19d-583948adc7b5.png)

**Comment by Trenly** [comment] 2022-02-17 05:12
I see now that it isn't working, and I'm almost certain its because it isn't properly interpreting `${GITHUB_REF#refs/*/}`

As for the `#ifndef Version`, as far as I know, that doesn't check for if the version is null, it just checks to make sure that the version was defined. Technically, it was defined as null or empty when the command line called inno setup, which is still considered defined.

Regarding the `[registry]` section, this is actually not needed for inno setup. You can see this in the `AppName=` where that value is what gets added as the DisplayName registry entry. The root cause here is just that it isn't fetching the tag correctly

**Comment by ehawman** [comment] 2022-02-17 20:28
Ah I see. That makes sense. 

https://docs.github.com/en/actions/learn-github-actions/environment-variables

<html>
<body>


GITHUB_REF_NAME | The branch or tag name that triggered the workflow run. For example, feature-branch-1.
-- | --



</body>
</html>

Would this do it? I have no familiarity with YAML, but based on your `${GITHUB_REF#refs/*/}`, it looks like you wanted to pull the wildcard out of the GITHUB_REF variable. GITHUB_REF_NAME appears to already do that.

So https://github.com/hydrusnetwork/hydrus/blob/e327c03caf032b846a4213b3124c5699274ee474/.github/workflows/release.yml#L196

would become `           ISCC.exe InnoSetup.iss /DVersion=${GITHUB_REF_NAME} `, I think?

**Comment by Trenly** [comment] 2022-02-17 21:04
> Ah I see. That makes sense.
> 
> https://docs.github.com/en/actions/learn-github-actions/environment-variables
> 
> GITHUB_REF_NAME	The branch or tag name that triggered the workflow run. For example, feature-branch-1.
> Would this do it? I have no familiarity with YAML, but based on your `${GITHUB_REF#refs/*/}`, it looks like you wanted to pull the wildcard out of the GITHUB_REF variable. GITHUB_REF_NAME appears to already do that.
> 
> So
> 
> https://github.com/hydrusnetwork/hydrus/blob/e327c03caf032b846a4213b3124c5699274ee474/.github/workflows/release.yml#L196
> 
> would become ` ISCC.exe InnoSetup.iss /DVersion=${GITHUB_REF_NAME}`, I think?

That makes sense to me; I was trying to do it based on the full ref and the solutions here, but the ref name is probably a better way of doing it

https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions
https://github.community/t/how-to-get-just-the-tag-name/16241

**Comment by hydrusnetwork** [comment] 2022-03-01 04:05
Hey, thank you for this report. I am sorry I am to it late. I am afraid I am not very expert at Inno or Github workflow scripting, so some of your discussion here went over my head. But I think I have it fixed now.

Note that line was a little different in master:
https://github.com/hydrusnetwork/hydrus/blob/63c992048ca1d060391ce7e6a69576ec65e77d8f/.github/workflows/release.yml#L219

The `${GITHUB_REF##*/v}` part is supposed to convert whatever that starts at (I think `refs/tags/v474`?) to `474`. It is used again later in the release script (to name the final build files with version number) and it is good there. But I think this is bash environment variable reference stuff (and the ## stuff too) and so only works in the Linux shell. Since Inno is happening on a Windows machine, it needs to be different.

To get around the issue entirely, I read up on how github contexts work and replaced it with this:
https://github.com/hydrusnetwork/hydrus/blob/3a863b182a4482a4638d5b9be271266d3e6f675f/.github/workflows/release.yml#L219

And just did a test build. This correctly places the text there and it propagates to the installer executable, but for a normal build that version text will be 'v474', with 'v' at the front. There didn't seem to be an easy way to slice a github Context variable to get just '474', so to get this we would probably have to do a similar echo trick as we do later for the filenames to establish a new environment variable with Powershell and whatever text modification tools that has. Do you know if this is important for winget, or will it parse that and do v474 < v475 style comparisons correct? If it can handle 'v474', we are all set for next release to fix this.

**Comment by Trenly** [comment] 2022-03-01 04:26
Winget should be able to properly compare even with the v in front

**Comment by hydrusnetwork** [comment] 2022-03-02 01:05
Fantastic. This will push in tomorrow's tagged release build, so fingers crossed this is fixed from now on.

@ehawman Please let me know if this gives any more trouble in future.

**Closed** 2022-03-02 21:44 UTC
Labels: bug

**Comment by ehawman-rosenberg** [comment] 2022-03-04 04:15
![image](https://user-images.githubusercontent.com/81652082/156696175-64bba298-2edc-476c-beef-5a19ed16a531.png)

Currently 474 is seen as more recent than v475, which is prompting an "update". The winget package hasn't been updated to 475 yet, so we have yet to see if the "v" issue will be a problem. @hydrusnetwork  are you the one submitting [these manifests](https://github.com/microsoft/winget-pkgs/tree/master/manifests/h/HydrusNetwork/HydrusNetwork) or is it someone else doing it on your behalf?

In any case, yay! It's not an unknown package anymore! Progress!

**Comment by ehawman** [comment] 2022-03-04 04:17
EDIT: Used wrong account before

![image](https://user-images.githubusercontent.com/81652082/156696175-64bba298-2edc-476c-beef-5a19ed16a531.png)

Currently 474 is seen as more recent than v475, which is prompting an "update". The winget package hasn't been updated to 475 yet, so we have yet to see if the "v" issue will be a problem. @hydrusnetwork  are you the one submitting [these manifests](https://github.com/microsoft/winget-pkgs/tree/master/manifests/h/HydrusNetwork/HydrusNetwork) or is it someone else doing it on your behalf?

In any case, yay! It's not an unknown package anymore! Progress!

**Comment by Trenly** [comment] 2022-03-04 04:40
> EDIT: Used wrong account before
> 
> ![image](https://user-images.githubusercontent.com/81652082/156696175-64bba298-2edc-476c-beef-5a19ed16a531.png)
> 
> Currently 474 is seen as more recent than v475, which is prompting an "update". The winget package hasn't been updated to 475 yet, so we have yet to see if the "v" issue will be a problem. @hydrusnetwork are you the one submitting [these manifests](https://github.com/microsoft/winget-pkgs/tree/master/manifests/h/HydrusNetwork/HydrusNetwork) or is it someone else doing it on your behalf?
> 
> In any case, yay! It's not an unknown package anymore! Progress!

It will take some time for winget to recognize rhe sorting; Older versions will have to be updated ro manifest schema 1.1.0 and have their versions updated to match the vXXX

I’ll be working on that so the changes should go through in the next few days

**Comment by Zweibach** [comment] 2022-03-05 21:43
@ehawman Dev only maintains the github releases. Everything else are third parties.
