### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy.core'

### ISSUE THREAD

**Issue by Alpha5361** [hydrusnetwork/hydrus#1131] opened 2022-04-29 18:25 UTC
### Hydrus version

v482

### Operating system

Linux (specify distro and version in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

Installed via the aur
Linux distribution Manjaro

### Bug description and reproduction

Bug Description and Reproduction
The Hydrus client is not starting and I have no access to the gui.
After reading the error message I thought it would be resolved by waiting for an update to numpy and or Hydrus. So I don't remember all of the details surrounding the start of the problem. But I think I updated my system and the client started failing.

Steps Taken
1. I have attempted to update numpy using `pip install numpy --upgrade`,
2. Then I attempted to reinstall numpy through `pip uninstall numpy` and `pacman -S python-numpy`
3. I have also tried to update Hydrus using `yay -S hydrus`.

I must admit I am generally ignorant about python libraries. So I don't know if this is the correct way to reinstall a python library on Manjaro for an app like Hydrus, or in general.

### Log output

```text
v482, 2022/04/27 19:19:29: hydrus client started
v482, 2022/04/27 19:19:29: hydrus client failed
v482, 2022/04/27 19:19:29: Traceback (most recent call last):
  File "/opt/hydrus/hydrus/hydrus_client.py", line 213, in boot
    from hydrus.client import ClientController
  File "/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/opt/hydrus/hydrus/client/ClientController.py", line 27, in <module>
    from hydrus.client import ClientCaches
  File "/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/opt/hydrus/hydrus/client/ClientCaches.py", line 9, in <module>
    from hydrus.core import HydrusImageHandling
  File "/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/opt/hydrus/hydrus/core/HydrusImageHandling.py", line 4, in <module>
    import numpy.core.multiarray # important this comes before cv!
  File "/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'numpy.core'

v482, 2022/04/27 19:19:29: hydrus client shut down
```

**Comment by bbappserver** [comment] 2022-05-15 11:15
@Alpha5361 It looks like whatever package you are installing from is malformed.  Hydrus does not officially support 3rd party distributions.  Here are some workarounds that might help.
1. Run `pip3 install numpy --upgrade`, `pip` may refer to `pip` for `python2` under your system.
2. Run hydrus from source. It seems whoever built your package screwed it up, but it is really easy to just run `pip3 install -r requirements.ubuntu.txt && python3 client.py` which will probably be adequate for most linux distros.

**Comment by Alpha5361** [comment] 2022-05-18 18:58
@bbappserver
Your `pip3` workaround didn't work for me.
I am having trouble building from source.

https://pastebin.com/tebR2qV2
```
pip3 install -r requirements_ubuntu.txt && python3 client.py
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: beautifulsoup4>=4.0.0 in /usr/lib/python3.10/site-packages (from -r requirements_ubuntu.txt (line 1)) (4.10.0)
Collecting cbor2
  Using cached cbor2-5.4.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (224 kB)
Requirement already satisfied: chardet>=3.0.4 in /usr/lib/python3.10/site-packages (from -r requirements_ubuntu.txt (line 3)) (4.0.0)
Collecting cloudscraper>=1.2.33
  Using cached cloudscraper-1.2.60-py2.py3-none-any.whl (97 kB)
Requirement already satisfied: html5lib>=1.0.1 in /usr/lib/python3.10/site-packages (from -r requirements_ubuntu.txt (line 5)) (1.1)
Requirement already satisfied: lxml>=4.5.0 in /usr/lib/python3.10/site-packages (from -r requirements_ubuntu.txt (line 6)) (4.8.0)
Requirement already satisfied: lz4>=3.0.0 in /usr/lib/python3.10/site-packages (from -r requirements_ubuntu.txt (line 7)) (3.1.10)
Requirement already satisfied: nose>=1.3.0 in /usr/lib/python3.10/site-packages (from -r requirements_ubuntu.txt (line 8)) (1.3.7)
Requirement already satisfied: numpy>=1.16.0 in /usr/lib/python3.10/site-packages (from -r requirements_ubuntu.txt (line 9)) (1.22.3)
Collecting opencv-python-headless<=4.5.3.56,>=4.0.0
  Using cached opencv-python-headless-4.5.3.56.tar.gz (89.2 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [1066 lines of output]
```
...  
```
note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]
```

It does this on the source code obtained from `git clone` and the release version of the source code.

It looks like gcc is having trouble compiling two .c files in numpy/core/
specifically these two lines.
1. line 796 numpy/core/src/multiarray/scalartypes.c.src:2967:27: error: incompatible type for argument 1 of ‘_Py_HashDouble’
2. line 960 numpy/core/src/multiarray/nditer_api.c:1684:24: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]

**Comment by hydrusnetwork** [comment] 2022-05-24 22:58
Hey, sorry to see you are having trouble. If pip cannot building numpy and/or opencv here, I think there may just be an OS/architecture problem. Building numpy used to be a real pain on some machines, but these days it is usually easy and only takes a few seconds. I see in your log it is moaning about arm64 in some way, so I suspect it is having trouble finding a pre-built easy-install route for your platform. If your machine uses an extremely new version of python, that may also be a problem.

I think your best bet is to try hydrus on a different (maybe more mainstream?) machine. You could also try contacting the guys who manage the Arch package or whatever you are using here, but this seems a little more low level and there may just not be an easy solution.

Sorry that I cannot help more! I am now closing this issue, since it is not a bug with hydrus.

**Closed by hydrusnetwork** 2022-05-24 22:58 UTC
Labels: bug, third-party

**Comment by ScoreUnder** [comment] 2022-05-26 00:38
Hi @Alpha5361 , I maintain the AUR package for Arch Linux. I don't know much about the differences Manjaro presents to the build system, but I would advise that you check that all base packages on your system are up-to-date (`pacman -Syu`). The AUR package for hydrus depends on numpy, so if you have installed it then you will have also installed numpy in the process. The fact that it cannot find numpy here suggests to me that you have an outdated numpy package.

As I mentioned in [this comment](https://aur.archlinux.org/packages/hydrus#comment-843829) on the AUR package, a likely culprit for this is that the package in question (here `python-numpy`) is built for an old version of Python and needs reinstallation. If you have `python-numpy-git`, `python-numpy-mkl`, or otherwise some AUR-built version of numpy, then this explanation is especially likely.

If you run the command mentioned in that comment, `pacman -Qo /usr/lib/python3.9`, it should say:
```
error: No package owns /usr/lib/python3.9
```
If you instead get shown a list of packages, then all of those packages are out of date and need reinstallation.

If this isn't the issue, hit me up @ score#6846 and I'll see if I can help.
