### ISSUE TITLE
Import and page based on Pixiv's original file name option

### ISSUE THREAD

**Issue by Phooh** [hydrusnetwork/hydrus#182] opened 2016-06-21 05:32 UTC
You can skip this if you already know how Pixiv image naming works. What I like about Pixiv is the way they name their images by using it's image ID for exaple "21545164_p0". The first set of numbers makes it easier to find where/who it's from on Pixiv, kind of like another way of using iqdb. By going to, say:
www.pixiv.net/member_illust.php?mode=medium&illust_id=56669254
By replacing "56669254" with "21545164" from earlier I can get straight to the image and find out who's it's from. The "_p0" or any other number represents the number of pages if and image has a set collection of images that should be or go in a certain order. For example "17128627_p0" and "17128627_p1" and "17128627_p2" and so on. There's also names like "10360226_p0_master1200", I think "master" is the full size versions. I can't remember.

What I want to know is, if it was possable to add an option for Hydrus to import and auto page images based on "_p#" from the original file names in the menu right before you go to import. A Pixiv option basically. Or maybe if there's 2 or more images with the same first set of digits as before(17128627_p0, 17128627_p1) because I think Pixiv started forcing all images to have "_p0" even if they don't have or aren't in a collection some time ago. Makes it easier for those who already had a huge load of images before using Hydrus.

**Comment by KriPet** [comment] 2016-06-23 03:01
Seems to be a duplicate of #58

**Comment by mserajnik** [comment] 2020-06-13 19:17
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).

**Closed by mserajnik** 2020-06-13 19:17 UTC
Labels: old-issue
