### ISSUE TITLE
How to add (and replace) namespaces to multiple tags? Does this feature exist in hydrus?

### ISSUE THREAD

**Issue by regurafan** [hydrusnetwork/hydrus#1472] opened 2023-11-04 14:16 UTC
For example: given that I have a list of tags:

blue eyes
brown eyes
green eyes
purple eyes
yellow eyes
closed eyes
red eyes

or

unknown:blue eyes
unknown:brown eyes
unknown:green eyes
unknown:purple eyes
unknown:yellow eyes
unknown:closed eyes
unknown:red eyes

How to add/replace the "eyes" namespace in all of them?

eyes: blue eyes
eyes:brown eyes
eyes:green eyes
eyes:purple eyes
eyes:yellow eyes
eyes:closed eyes
eyes:red eyes

Manually I would do for each tag:

1. Select all files containing the "blue eyes" tag
2. I would add "eyes:blue eyes" to another service.
3. Delete "blue eyes" from the service where the tag is located

Is there a feature in Hydrus that does this for multiple tags?

If not, would it be possible to do it, for example, through SQLiteStudio?

I know very little about SQL but I think I can learn how to use it. The most I got was:

(I backed up the hydrus database)
1. Open client.master.db and
2. I located the `namespace`, `tag` and `subtag` tables.
3. I tested the command `UPDATE subtags SET subtag="new tag" WHERE subtag="old tag"`

I saw that things inside client.master.db are separate. I was even able to imagine a reasoning (which made sense to me at first) of how it would be to link the namespace to the tag/subtag through the ID columns, but it probably wouldn't work out the way I imagined because I tested doing `UPDATE subtags SET subtag=" new tag" WHERE subtag="old tag"` and when I opened hydrus it: did not find the new tag, identified a remnant of the old one but did not locate the files when filtering by the old one.

**Comment by Zweibach** [comment] 2023-11-04 14:29
Duplicate of #585

**Closed by Zweibach** 2023-11-04 14:29 UTC
Labels: feature-request
