### ISSUE TITLE
Add parent/child files

### ISSUE THREAD

**Issue by mukiw1** [hydrusnetwork/hydrus#1550] opened 2024-05-09 02:57 UTC
For files that require other files to be relevant, you can set a parent file that connects to a child file and vice versa. Ideally, there would also be a way to see the parent and child files together in a custom order, possibly in a new tab.

This could be in a menu much like the parent/child tags. unlike the parent/child tags, however, where there are possibly multiple parent tags, there would just be 1 parent. Otherwise, there wouldn't be a point considering that would be the same thing as a tag.

the child file might have a button/link to go to the parent file and or see the entire group while the parent file could have just the see all in group button.

An example would be for a comic with each page being its own file with its own tags. Each page would be a child file and the cover would be the parent. When you went to see them all they would be in a custom order so that someone doesn't have to rely on which file was imported first.

**Comment by Charsy89** [comment] 2024-05-09 03:43
You shouldn't rely on file import times to order a series of files. Use page: tags instead. page:1, page:2, page:3... etc. You can select multiple files and _right-click_ -> _manage_ -> _tags_, then hit the ± button to tag them like this.

And this feature already exists, if I'm understanding your request properly.
_Right-click a file_ -> _manage_ -> _file relationships_ is where you'll find this functionality. You might set all the files as alternates of each other, but that's just my workflow.

**Comment by Zweibach** [comment] 2024-05-24 14:31
Duplicate of #310

**Closed by Zweibach** 2024-05-24 14:31 UTC
Labels: feature-request
