### ISSUE TITLE
Hide Replaced Tag

### ISSUE THREAD

**Issue by Nerethenam** [hydrusnetwork/hydrus#1649] opened 2024-12-19 05:09 UTC
The option to hide tags replaced with siblings so when you manage tags instead of the window showing multiple duplicates of the sibling tag from all of the replaced tags, it just shows the one tag. It would make looking over tags much easier and more organized.

Real Example
artist:kakure_eria -> creator:kakure eria
creator:haku3490 -> creator:kakure eria
creator:影おじ (隠れエリア) -> creator:kakure eria
creator:隠れエリア -> creator:kakure eria
haku3490 -> creator:kakure eria
kakure eria -> creator:kakure eria
pixiv id:6570768 -> creator:kakure eria
pixiv profile:6570768 -> creator:kakure eria

Proposed feature would just show
creator:kakure eria

**Comment by Zweibach** [comment] 2024-12-20 23:13
Duplicate of #995

**Closed by Zweibach** 2024-12-20 23:13 UTC
Labels: feature-request
