### ISSUE TITLE
watchers/downloads stopped

### ISSUE THREAD

**Issue by alidan** [hydrusnetwork/hydrus#898] opened 2021-06-04 07:59 UTC
my watchers and downloaders stopped

## Environment

Hydrus version: 439
Platform: windows
OS specifics: windows 7

## What happens

I noticed after I imported some things that nothing was happening, turns out all watcher related stuff was not working. in the corner, I think there was a notice about the programs being asleep or waking up, I can't remember and didn't think to screenshot it at the time, not fully putting 2 and 2 together, something like this has happened before several months/a year or so ago and im not sure if it was also the same issue then as now. 

## Steps to reproduce

1. I have no idea, I think the program went idle and failed to un idle. 

## Desired outcome

bring awareness to the potential issue. 

## Error message / Log file / Screenshots

there is nothing in the log about what happened. ill try to be aware enough to screenshot the text next time something like this happens.

**Comment by hydrusnetwork** [comment] 2021-09-08 00:09
Thank you for this report. I believe this may have been caused by some badly handled network infrastructure errors, which were causing work slots to be occupied and not freed up, leaving everything on 'pending' status. With luck this is fixed in tomorrow's release, but please reopen this issue and let me know if you get it again and have any more information.

**Closed** 2021-09-08 21:42 UTC
Labels: bug
