### ISSUE TITLE
Playing video on hydrus while ASIO driver is active causes hydrus to crash

### ISSUE THREAD

**Issue by aaronata** [hydrusnetwork/hydrus#973] opened 2021-09-02 06:35 UTC
### Hydrus version

453

### Operating system

Windows 10

### Install method

Installer

### Bug description and reproduction

ASIO (Audio Stream Input-Output) drivers are used to allow programs to take direct control of the computers soundcard.

Normally this will disable audio from other programs, needing you to restart them after the ASIO driver is closed to regain sound from said programs. When an ASIO driver is running, putting Hydrus in a state where it needs to output audio, playing a video, will instead cause Hydrus to crash. 

To recreate:
1) Open Hydrus.
2) Open program that utilizes ASIO drivers such as Adobe Premiere, FL Studio, or Ableton. (or use this audio test software i found if you don't have any of the above, link at bottom)
3) Change audio mode to ASIO in program's settings.
4) Open/click on video in Hydrus that contains audio.
5) ???
6) Profit

The ASIO testing software that also works to crash Hydrus:
http://www.tropicalcoder.com/ASIOTestSigGen.htm

### Log output

```text
No errors in the log from Hydrus installed from binary. Couldn't test with Hydrus running from source.
```

**Comment by spaghetti-guy** [comment] 2021-09-23 04:01
Doesn't seem to be exclusive to ASIO as I just had this happen while listening to music in MusicBee with the output set as WASAPI (Exclusive). For reference, exclusive WASAPI also disables audio from other programs, though it's done in a different way, iirc. I happened to check Windows event viewer and my crash produced the following error:

> Faulting application name: client.exe, version: 0.0.0.0, time stamp: 0x61062592
Faulting module name: msvcrt.dll, version: 7.0.19041.546, time stamp: 0x564f9f39
Exception code: 0xc0000005
Fault offset: 0x000000000005db22
Faulting process id: 0x3f70
Faulting application start time: 0x01d7b02ddd125c69
Faulting application path: C:\Miscellaneous Programs\Hydrus\client.exe
Faulting module path: C:\WINDOWS\System32\msvcrt.dll
Report Id: 3f59f3d4-6989-4b6e-b0ac-52d9ac204dda
Faulting package full name: 
Faulting package-relative application ID: 

I can confirm the crash occurred right as I clicked a video with sound.

**Comment by hydrusnetwork** [comment] 2021-09-29 01:07
Thank you for these reports. I am sorry to say that I have never used either ASIO or WASAPI before, so I am a bit new to this concept. Also, unfortunately, my dev machine does not seem to have ASIO driver support, so that test program will not boot for me!

For background, while searching around this problem, there are some mpv.conf settings that are related to this, and may be part of an answer, here: https://mpv.io/manual/master/#options-audio-exclusive

That said, we need to gather some more information. I have added an 'mpv report mode' to tomorrow's release, under the _help->debug->report modes_ menu, that will spam lots of mpv information to the hydrus log (in your 'install_dir/db' directory). When it is convenient, please run this report mode and initiate the crash (a fresh extract of the client is fine if you do not want to purposefully crash your IRL install). Let's see what the last few lines were in the log before the crash, and we can see if there are any more specifics.

The way I embed mpv into the program is quite duct-taped I am afraid, with several hacky steps to stop crashes even when the OS driver situation is normal, so I cannot promise an excellent solution here. I may be a bit out of my depth.

**Comment by spaghetti-guy** [comment] 2021-09-30 03:00
I appreciate you looking into this. Log is below. While doing some testing, I tried adding the ["audio fallback to null" switch](https://mpv.io/manual/master/#options-audio-fallback-to-null) to the mpv.conf for Hydrus and was still receiving crashes. However, when I added "ao=NULL" to the config file, I did not receive any crash. That's odd because the "audio-fallback-to-null" switch looks like it's supposed to do the same thing if the audio device can't be opened (as would be the case with WASAPI or ASIO). I've never used that switch, though, so maybe there's something else going on.

The exact steps I used to create the log are: (this log does not include any mpv.conf modifications I mentioned above)

1. [Install Foobar2000](https://www.foobar2000.org/getfile/foobar2000_v1.6.7.exe) in portable mode 
2. Install the [component enabling WASAPI output](https://www.foobar2000.org/components/view/foo_out_wasapi) (this is not hardware specific if you are interested in testing yourself).
3. Set Foobar to use "WASAPI (event)" for my default audio output device in Preferences > Playback > Output > Device
4. Play any song
5. Open a fresh Hydrus client with a brand new test database
6. Play a video with sound
7. Crash


[client - 2021-09.log](https://github.com/hydrusnetwork/hydrus/files/7256206/client.-.2021-09.log)

**Comment by spaghetti-guy** [comment] 2021-09-30 03:12
For reference, I will also include a log where I skip steps 1-4 above. So this is just playing the same video on the same hardware for comparison. This log, of course, has no crash because the file played successfully
[client - 2021-09 (no music).log](https://github.com/hydrusnetwork/hydrus/files/7256364/client.-.2021-09.no.music.log)

**Comment by spaghetti-guy** [comment] 2021-09-30 03:45
Ah, sorry for triple posting, but I think I figured out a solution. I noticed in the logs that mpv was defaulting to WASAPI for output even when Foobar was not running, so I added the following two lines to the mpv.conf in the database folder ("C:\Miscellaneous Programs\Hydrus\test_db" in my case):

```
ao=wasapi
audio-fallback-to-null=yes
```

What this does is sets the output device to WASAPI (even though it's already defaulting to that) and allows it to fall back to NULL if it fails to initialize that device. It's just weird that adding the fallback line alone doesn't work. The 2 lines shouldn't cause issues for any Windows version of Hydrus as it appears WASAPI is just mpv's standard audio output device on Windows. This should be verifiable by simply running the mpv debug you mentioned and playing any video with audio in Hydrus. You should be able to see a bunch of hits for "wasapi" in the logs.

@aaronata - Want to see if adding those two lines works for you? Schiit got rid of their ASIO driver for the Modius so I'm unable to test ASIO.

**Comment by aaronata** [comment] 2021-09-30 11:50
These two line indeed fixed the issue and it no longer crashes with ASIO.

**Comment by hydrusnetwork** [comment] 2021-11-02 23:53
@spaghetti-guy Thank you for this excellent fix. I regret I could not be more help. I have written a new help text file in the db directory with these mpv.conf lines in the hopes other users in this situation can benefit too.

I will close this for now, but please reopen if there are further problems here!

**Closed by hydrusnetwork** 2021-11-02 23:53 UTC
Labels: bug
