### ISSUE TITLE
Option to display keyboard mappings with media viewer/thumbnails window open for reference

### ISSUE THREAD

**Issue by novakda** [hydrusnetwork/hydrus#1370] opened 2023-05-21 22:57 UTC
**Note:** this is distinct from #1092.

It can be difficult to remember key mappings for shortcuts, especially if you have a lot of them and change them frequently for tagging as I do.

Please add a way to display a list of keyboard shortcuts at the same time as thumbnail and media viewer windows, for example a separate window or translucent overlay that still allows the keys to be used.

Alternatively, if the edit shortcuts window could be non-modal, it would allow it to be open at the same time as the media viewer and thumbnails and serve a similar purpose.  I don't know if this is reasonable technically (i.e. if the system relies on these windows being modal).

**Comment by Zweibach** [comment] 2023-05-27 19:33
Duplicate of #487

**Closed by Zweibach** 2023-05-27 19:33 UTC
Labels: feature-request
